# TileDB-SOMA Object Operations: Examples

This notebook contains example commands and common usage patterns for opening, inspecting, interacting and working with TileDB-SOMA objects.
This contains only some relevant examples and is not exhaustive.

Use conda env `tiledbsoma` (`/opt/mamba/envs/tiledbsoma/`) on scds-c server.

In [2]:
import tiledbsoma as soma
import scanpy as sc
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import os

## Experiments

### Accessing TileDB-SOMA Experiment

Example experiment: `/wip/scds/delivery-zips/batch14/GSE76312/tiledbsoma_expt`

In [ ]:
expt_uri = "/wip/scds/delivery-zips/batch14/GSE76312/tiledbsoma_expt"
expt = soma.Experiment.open(expt_uri)
print(expt)

<Experiment '/wip/scds/delivery-zips/batch14/GSE76312/tiledbsoma_expt' (open for 'r') (2 items)
    'ms': 'file:///wip/scds/delivery-zips/batch14/GSE76312/tiledbsoma_expt/ms' (unopened)
    'obs': 'file:///wip/scds/delivery-zips/batch14/GSE76312/tiledbsoma_expt/obs' (unopened)>

### Access various components of the dataset

**Access `obs` (SOMA dataframe with cell level annotations)**

In [ ]:
print(expt.obs)
expt.obs.read().concat().to_pandas()

<DataFrame 'file:///wip/scds/delivery-zips/batch14/GSE76312/tiledbsoma_expt/obs' (open for 'r')>

,soma_joinid,obs_id,orig.ident,nFeature_RNA,nCount_RNA,percent.mt,percent.ribo,percent.hemoglobin,S_score,G2M_score,...,popv_prediction_ontology_name,popv_prediction_ontology_id,popv_prediction_score,popv_prediction_depth,popv_prediction_onclass_relative_depth,popv_parent_ontology_name,popv_parent_ontology_id,cancerFinder_score,cancerFinder_call,cancerFinder_call_healthy_samples_censored
0,0,K562_GSM1980077,K562,5288.0,690894.0,11.777060,3.749490,0.099002,61.443643,52.549784,...,erythroid progenitor cell,CL:0000038,4,5,-1,erythroid progenitor cell,CL:0000038,0.998671,Tumor,Tumor
1,1,K562_GSM1980078,K562,3678.0,441474.0,13.699108,3.549473,0.164902,43.399690,64.752285,...,erythroid progenitor cell,CL:0000038,3,5,-1,hematopoietic precursor cell,CL:0008001,0.995290,Tumor,Tumor
2,2,K562_GSM1980079,K562,4056.0,1310139.0,10.594372,4.497691,0.305235,-66.608527,-59.887061,...,common myeloid progenitor,CL:0000049,3,4,0,hematopoietic precursor cell,CL:0008001,0.979533,Tumor,Tumor
3,3,K562_GSM1980080,K562,4589.0,1921304.0,10.378992,3.829430,0.356060,-74.980930,-105.904329,...,erythroid progenitor cell,CL:0000038,3,5,-1,progenitor cell,CL:0011026,0.995342,Tumor,Tumor
4,4,K562_GSM1980082,K562,3509.0,1376365.0,13.450429,3.304792,0.377226,-61.651628,-37.041270,...,erythroid progenitor cell,CL:0000038,3,5,-1,hematopoietic precursor cell,CL:0008001,0.984695,Tumor,Tumor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2031,2031,OX1705_GSM2509122,OX1705,5805.0,1986606.0,9.244661,9.639556,0.000000,31.501874,-50.146063,...,hematopoietic stem cell,CL:0000037,6,4,0,hematopoietic stem cell,CL:0000037,0.948704,Tumor,Tumor
2032,2032,OX1705_GSM2509123,OX1705,4955.0,1869256.0,11.906074,7.911971,0.000053,135.464529,-49.002157,...,hematopoietic stem cell,CL:0000037,5,4,0,hematopoietic stem cell,CL:0000037,0.884899,Tumor,Tumor
2033,2033,OX1705_GSM2509124,OX1705,5705.0,2326327.0,9.935705,16.355482,0.000000,-84.399503,-68.347393,...,hematopoietic stem cell,CL:0000037,6,4,0,hematopoietic stem cell,CL:0000037,0.949036,Tumor,Tumor
2034,2034,OX1705_GSM2509125,OX1705,4862.0,1436412.0,7.186448,9.320237,0.000000,-46.362971,-41.904315,...,hematopoietic stem cell,CL:0000037,6,4,0,hematopoietic stem cell,CL:0000037,0.865040,Tumor,Tumor
2035,2035,OX1705_GSM2509126,OX1705,5864.0,2992370.0,12.604725,8.078279,0.000000,-91.854595,-125.115138,...,hematopoietic stem cell,CL:0000037,6,4,0,hematopoietic stem cell,CL:0000037,0.913403,Tumor,Tumor

**Access the SOMA Measurement containing the RNA counts data**

In [16]:
expt.ms["RNA"]

<Measurement 'file:///wip/scds/delivery-zips/batch14/GSE76312/tiledbsoma_expt/ms/RNA' (open for 'r') (6 items)
    'X': 'file:///wip/scds/delivery-zips/batch14/GSE76312/tiledbsoma_expt/ms/RNA/X' (unopened)
    'obsm': 'file:///wip/scds/delivery-zips/batch14/GSE76312/tiledbsoma_expt/ms/RNA/obsm' (unopened)
    'obsp': 'file:///wip/scds/delivery-zips/batch14/GSE76312/tiledbsoma_expt/ms/RNA/obsp' (unopened)
    'uns': 'file:///wip/scds/delivery-zips/batch14/GSE76312/tiledbsoma_expt/ms/RNA/uns' (unopened)
    'var': DataFrame 'file:///wip/scds/delivery-zips/batch14/GSE76312/tiledbsoma_expt/ms/RNA/var' (open for 'r')
    'varm': 'file:///wip/scds/delivery-zips/batch14/GSE76312/tiledbsoma_expt/ms/RNA/varm' (unopened)>


**Access `var` (SOMA dataframe with the feature-level annotations)**

In [17]:
expt.ms["RNA"].var.read().concat().to_pandas()

,soma_joinid,var_id,gene_ids,feature_types,mt,ribo,hemoglobin,gene_symbols,gene_symbols_2024A,genome,highly_variable,means,dispersions,dispersions_norm,mean,std
0,0,TSPAN6,ENSG00000000003,Gene Expression,False,False,False,TSPAN6,TSPAN6,GRCh38,True,4.958227e-02,1.729043,0.996466,0.020592,0.168125
1,1,TNMD,ENSG00000000005,Gene Expression,False,False,False,TNMD,TNMD,GRCh38,False,1.000000e-12,NaN,0.000000,0.000000,1.000000
2,2,DPM1,ENSG00000000419,Gene Expression,False,False,False,DPM1,DPM1,GRCh38,False,3.718615e-01,1.462034,-1.026260,0.201106,0.472227
3,3,SCYL3,ENSG00000000457,Gene Expression,False,False,False,SCYL3,SCYL3,GRCh38,True,1.780046e-01,2.156234,1.160082,0.069409,0.318505
4,4,C1orf112,ENSG00000000460,Gene Expression,False,False,False,C1orf112,C1orf112,GRCh38,True,1.203737e-01,1.574168,0.937148,0.055430,0.266165
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36517,36517,CRIPAK,ENSG00000288380,Gene Expression,False,False,False,CRIPAK,NA,GRCh38,True,5.881637e-02,2.104976,1.140449,0.020208,0.184191
36518,36518,AL109627.1,ENSG00000288398,Gene Expression,False,False,False,AL109627.1,ENSG00000288398,GRCh38,True,4.192125e-02,1.382822,0.863862,0.021468,0.148799
36519,36519,AC024558.2,ENSG00000288436,Gene Expression,False,False,False,AC024558.2,NA,GRCh38,False,2.071631e-06,-5.468431,-1.760189,0.000002,0.000093
36520,36520,AL512357.2,ENSG00000288459,Gene Expression,False,False,False,AL512357.2,ENSG00000288459,GRCh38,False,4.285502e-06,-4.938561,-1.557247,0.000004,0.000175
36521,36521,AL138899.3,ENSG00000288460,Gene Expression,False,False,False,AL138899.3,SMIM42,GRCh38,False,6.041154e-06,-5.421509,-1.742217,0.000006,0.000163

### Slicing and Filtering Experiments

**Querying for cells with nFeature_RNA > 1000 and genes that are highly_variable**

The query result object (`query`) allows to inspect the query result and selectively access the data instead of loading the entire dataset

In [18]:
query = soma.ExperimentAxisQuery(
    experiment=expt,
    measurement_name="RNA",
    obs_query=soma.AxisQuery(
        value_filter="nFeature_RNA > 1000",
    ),
    var_query=soma.AxisQuery(
        value_filter="highly_variable == True",
    ),
)

**See how many cells and genes are returned with the above query**

In [19]:

(query.n_obs, query.n_vars)

(2036, 9749)

**Access the DataFrame containing the annotations for all cells returned by the above query**

In [20]:
query.obs().concat().to_pandas()

,soma_joinid,obs_id,orig.ident,nFeature_RNA,nCount_RNA,percent.mt,percent.ribo,percent.hemoglobin,S_score,G2M_score,...,popv_prediction_ontology_name,popv_prediction_ontology_id,popv_prediction_score,popv_prediction_depth,popv_prediction_onclass_relative_depth,popv_parent_ontology_name,popv_parent_ontology_id,cancerFinder_score,cancerFinder_call,cancerFinder_call_healthy_samples_censored
0,0,K562_GSM1980077,K562,5288.0,690894.0,11.777060,3.749490,0.099002,61.443643,52.549784,...,erythroid progenitor cell,CL:0000038,4,5,-1,erythroid progenitor cell,CL:0000038,0.998671,Tumor,Tumor
1,1,K562_GSM1980078,K562,3678.0,441474.0,13.699108,3.549473,0.164902,43.399690,64.752285,...,erythroid progenitor cell,CL:0000038,3,5,-1,hematopoietic precursor cell,CL:0008001,0.995290,Tumor,Tumor
2,2,K562_GSM1980079,K562,4056.0,1310139.0,10.594372,4.497691,0.305235,-66.608527,-59.887061,...,common myeloid progenitor,CL:0000049,3,4,0,hematopoietic precursor cell,CL:0008001,0.979533,Tumor,Tumor
3,3,K562_GSM1980080,K562,4589.0,1921304.0,10.378992,3.829430,0.356060,-74.980930,-105.904329,...,erythroid progenitor cell,CL:0000038,3,5,-1,progenitor cell,CL:0011026,0.995342,Tumor,Tumor
4,4,K562_GSM1980082,K562,3509.0,1376365.0,13.450429,3.304792,0.377226,-61.651628,-37.041270,...,erythroid progenitor cell,CL:0000038,3,5,-1,hematopoietic precursor cell,CL:0008001,0.984695,Tumor,Tumor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2031,2031,OX1705_GSM2509122,OX1705,5805.0,1986606.0,9.244661,9.639556,0.000000,31.501874,-50.146063,...,hematopoietic stem cell,CL:0000037,6,4,0,hematopoietic stem cell,CL:0000037,0.948704,Tumor,Tumor
2032,2032,OX1705_GSM2509123,OX1705,4955.0,1869256.0,11.906074,7.911971,0.000053,135.464529,-49.002157,...,hematopoietic stem cell,CL:0000037,5,4,0,hematopoietic stem cell,CL:0000037,0.884899,Tumor,Tumor
2033,2033,OX1705_GSM2509124,OX1705,5705.0,2326327.0,9.935705,16.355482,0.000000,-84.399503,-68.347393,...,hematopoietic stem cell,CL:0000037,6,4,0,hematopoietic stem cell,CL:0000037,0.949036,Tumor,Tumor
2034,2034,OX1705_GSM2509125,OX1705,4862.0,1436412.0,7.186448,9.320237,0.000000,-46.362971,-41.904315,...,hematopoietic stem cell,CL:0000037,6,4,0,hematopoietic stem cell,CL:0000037,0.865040,Tumor,Tumor
2035,2035,OX1705_GSM2509126,OX1705,5864.0,2992370.0,12.604725,8.078279,0.000000,-91.854595,-125.115138,...,hematopoietic stem cell,CL:0000037,6,4,0,hematopoietic stem cell,CL:0000037,0.913403,Tumor,Tumor

**Load the expression matrix (normalized counts) for the selected cells and genes as a Pandas DataFrame**

In [21]:
query.X(layer_name="data").tables().concat().to_pandas()

         soma_dim_0  soma_dim_1  soma_data
0                 0           3   0.834065
1                 0           4   0.083278
2                 0           6   1.203067
3                 0           9   0.014370
4                 0          16   0.014370
...             ...         ...        ...
4426712        2035       36029   0.003336
4426713        2035       36147   0.006661
4426714        2035       36317   0.215605
4426715        2035       36504   0.202045
4426716        2035       36514   0.757474

[4426717 rows x 3 columns]

**Load the raw counts**

In [22]:
query.X(layer_name="counts").tables().concat().to_pandas()

         soma_dim_0  soma_dim_1  soma_data
0                 0           3       90.0
1                 0           4        6.0
2                 0           6      161.0
3                 0           9        1.0
4                 0          16        1.0
...             ...         ...        ...
4426712        2035       36029        1.0
4426713        2035       36147        2.0
4426714        2035       36317       72.0
4426715        2035       36504       67.0
4426716        2035       36514      339.0

[4426717 rows x 3 columns]

## Collections

### List collections in the tiledbsoma_collections directory

In [3]:
collections_path = Path("/wip/scds/delivery-zips/tiledbsoma_collections/")
collections = [c for c in os.listdir(collections_path) if (collections_path / c).is_dir()]
for i, coll in enumerate(collections, start=1):
    print(f"{i}. {coll}")

1. Human_ss2
2. Mouse_ss2
3. Human_10x
4. Mouse_10x

### List experiments available in each collection

In [6]:
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', None)
from urllib.parse import urlparse
collections_path = Path("/wip/scds/delivery-zips/tiledbsoma_collections/")

rows = []

for path in collections_path.iterdir():
    if not path.is_dir():
        continue

    try:
        with soma.Collection.open(str(path)) as coll:
            collection_name = path.name

            for key in coll.keys():
                obj = coll[key]

                if isinstance(obj, soma.Experiment):
                    rows.append({
                        "Collection": collection_name,
                        "Experiment": key,
                        "Experiment_path": Path(urlparse(obj.uri).path)
                    })

    except Exception:
        continue

experiments = pd.DataFrame(rows)
experiments.index = experiments.index + 1
print(experiments)

   Collection               Experiment                                                  Experiment_path
1   Human_ss2         batch14_GSE76312         /wip/scds/delivery-zips/batch14/GSE76312/tiledbsoma_expt
2   Human_ss2      batch16_E-MTAB-6678      /wip/scds/delivery-zips/batch16/E-MTAB-6678/tiledbsoma_expt
3   Mouse_ss2      batch17_E-MTAB-8561      /wip/scds/delivery-zips/batch17/E-MTAB-8561/tiledbsoma_expt
4   Human_10x        batch14_GSE210395        /wip/scds/delivery-zips/batch14/GSE210395/tiledbsoma_expt
5   Human_10x        batch14_GSE248450        /wip/scds/delivery-zips/batch14/GSE248450/tiledbsoma_expt
6   Human_10x        batch14_GSE288490        /wip/scds/delivery-zips/batch14/GSE288490/tiledbsoma_expt
7   Human_10x       batch14_PRJEB39470       /wip/scds/delivery-zips/batch14/PRJEB39470/tiledbsoma_expt
8   Human_10x        batch15_GSE155512        /wip/scds/delivery-zips/batch15/GSE155512/tiledbsoma_expt
9   Human_10x        batch15_GSE227691        /wip/scds/delivery-zips/batch15/GSE227691/tiledbsoma_expt
10  Human_10x      batch16_E-MTAB-6701      /wip/scds/delivery-zips/batch16/E-MTAB-6701/tiledbsoma_expt
11  Human_10x        batch16_GSE253006        /wip/scds/delivery-zips/batch16/GSE253006/tiledbsoma_expt
12  Human_10x        batch17_GSE174653        /wip/scds/delivery-zips/batch17/GSE174653/tiledbsoma_expt
13  Mouse_10x        batch15_GSE155513        /wip/scds/delivery-zips/batch15/GSE155513/tiledbsoma_expt
14  Mouse_10x      batch17_E-MTAB-8562      /wip/scds/delivery-zips/batch17/E-MTAB-8562/tiledbsoma_expt
15  Mouse_10x  batch17_GSE180045_mouse  /wip/scds/delivery-zips/batch17/GSE180045_mouse/tiledbsoma_expt