# TileDB-SOMA Object Operations: Examples

This notebook contains example commands and common usage patterns for opening, inspecting, interacting and working with TileDB-SOMA objects.
This contains only some relevant examples and is not exhaustive.

Use conda env `tiledbsoma`

In [1]:
import tiledbsoma as soma
import tiledbsoma.io
import scanpy as sc
import anndata as ad
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
import s3fs
import os

## Experiments

### Accessing TileDB-SOMA Experiment

Example experiment: `s3://rancho-scrna-live/tiledb-experiments/batch1/GSE123813/tiledbsoma_expt`

In [2]:
expt_uri = "s3://rancho-scrna-live/tiledb-experiments/batch1/GSE123813/tiledbsoma_expt"
expt = soma.Experiment.open(expt_uri)
print(expt)

<Experiment 's3://rancho-scrna-live/tiledb-experiments/batch1/GSE123813/tiledbsoma_expt' (open for 'r') (2 items)
    'ms': 's3://rancho-scrna-live/tiledb-experiments/batch1/GSE123813/tiledbsoma_expt/ms' (unopened)
    'obs': 's3://rancho-scrna-live/tiledb-experiments/batch1/GSE123813/tiledbsoma_expt/obs' (unopened)>

### Access various components of the dataset

**Access `obs` (SOMA dataframe with cell level annotations)**

In [3]:
print(expt.obs)
expt.obs.read().concat().to_pandas()

<DataFrame 's3://rancho-scrna-live/tiledb-experiments/batch1/GSE123813/tiledbsoma_expt/obs' (open for 'r')>

,soma_joinid,obs_id,orig.ident,nFeature_RNA,nCount_RNA,percent.mt,high_mt,high_ct,doublet_score,predicted_doublet,...,donor_treatment_mesh_id,batch,collection,scds,dataset_data_type,curation_dataset_id,dataset_repository,dataset_repository_url,dataset_workflow,sample_number
0,0,GSM3721447_AAACCTGAGCGCCTCA-1,GSM3721447,1502,4678.0,1.859769,False,False,0.098627,False,...,NA,batch1,NA,True,GEX,GSE123813,NA,NA,cellranger_7,52
1,1,GSM3721447_AAACCTGAGGCAAAGA-1,GSM3721447,1156,2891.0,3.977862,False,False,0.093079,False,...,NA,batch1,NA,True,GEX,GSE123813,NA,NA,cellranger_7,52
2,2,GSM3721447_AAACCTGCAGACAAAT-1,GSM3721447,1712,5830.0,2.727273,False,False,0.051482,False,...,NA,batch1,NA,True,GEX,GSE123813,NA,NA,cellranger_7,52
3,3,GSM3721447_AAACCTGCATTCGACA-1,GSM3721447,1358,3972.0,3.172205,False,False,0.056291,False,...,NA,batch1,NA,True,GEX,GSE123813,NA,NA,cellranger_7,52
4,4,GSM3721447_AAACCTGGTCCCGACA-1,GSM3721447,2296,7875.0,3.085714,False,False,0.206497,False,...,NA,batch1,NA,True,GEX,GSE123813,NA,NA,cellranger_7,52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102330,102330,GSM3511746_TTCTTAGCATAAGACA-1,GSM3511746,4565,21899.0,2.675921,False,False,0.059406,False,...,NA,batch1,NA,True,GEX,GSE123813,NA,NA,cellranger_7,52
102331,102331,GSM3511746_TTGAACGAGTACTTGC-1,GSM3511746,4947,19979.0,4.089293,False,False,0.109375,False,...,NA,batch1,NA,True,GEX,GSE123813,NA,NA,cellranger_7,52
102332,102332,GSM3511746_TTGACTTTCCGTAGGC-1,GSM3511746,3797,18281.0,1.903616,False,False,0.059406,False,...,NA,batch1,NA,True,GEX,GSE123813,NA,NA,cellranger_7,52
102333,102333,GSM3511746_TTTACTGGTCGCGAAA-1,GSM3511746,4130,19409.0,2.266989,False,False,0.028754,False,...,NA,batch1,NA,True,GEX,GSE123813,NA,NA,cellranger_7,52
102334,102334,GSM3511746_TTTATGCAGATAGTCA-1,GSM3511746,3999,17188.0,2.117757,False,False,0.018088,False,...,NA,batch1,NA,True,GEX,GSE123813,NA,NA,cellranger_7,52

**Access the SOMA Measurement containing the RNA counts data**

In [4]:
expt.ms["RNA"]

<Measurement 's3://rancho-scrna-live/tiledb-experiments/batch1/GSE123813/tiledbsoma_expt/ms/RNA' (open for 'r') (6 items)
    'X': 's3://rancho-scrna-live/tiledb-experiments/batch1/GSE123813/tiledbsoma_expt/ms/RNA/X' (unopened)
    'obsm': 's3://rancho-scrna-live/tiledb-experiments/batch1/GSE123813/tiledbsoma_expt/ms/RNA/obsm' (unopened)
    'obsp': 's3://rancho-scrna-live/tiledb-experiments/batch1/GSE123813/tiledbsoma_expt/ms/RNA/obsp' (unopened)
    'uns': 's3://rancho-scrna-live/tiledb-experiments/batch1/GSE123813/tiledbsoma_expt/ms/RNA/uns' (unopened)
    'var': 's3://rancho-scrna-live/tiledb-experiments/batch1/GSE123813/tiledbsoma_expt/ms/RNA/var' (unopened)
    'varm': 's3://rancho-scrna-live/tiledb-experiments/batch1/GSE123813/tiledbsoma_expt/ms/RNA/varm' (unopened)>


**Access `var` (SOMA dataframe with the feature-level annotations)**

In [5]:
expt.ms["RNA"].var.read().concat().to_pandas()

,soma_joinid,var_id,gene_ids,highly_variable,means,dispersions,dispersions_norm,mean,std,genome,feature_types,mt
0,0,MIR1302-2HG,ENSG00000243485,False,6.135343e-05,0.558790,-0.973432,0.000036,0.005923,GRCh38,Gene Expression,False
1,1,FAM138A,ENSG00000237613,False,1.000000e-12,NaN,NaN,0.000000,1.000000,GRCh38,Gene Expression,False
2,2,OR4F5,ENSG00000186092,False,1.000000e-12,NaN,NaN,0.000000,1.000000,GRCh38,Gene Expression,False
3,3,AL627309.1,ENSG00000238009,False,3.780935e-03,1.148042,-0.129381,0.001923,0.047081,GRCh38,Gene Expression,False
4,4,AL627309.3,ENSG00000239945,False,1.062302e-04,1.405674,0.239654,0.000048,0.007914,GRCh38,Gene Expression,False
...,...,...,...,...,...,...,...,...,...,...,...,...
36596,36596,AC141272.1,ENSG00000277836,False,2.542288e-03,2.620404,1.979648,0.000664,0.035817,GRCh38,Gene Expression,False
36597,36597,AC023491.2,ENSG00000278633,False,1.000000e-12,NaN,NaN,0.000000,1.000000,GRCh38,Gene Expression,False
36598,36598,AC007325.1,ENSG00000276017,False,4.141517e-05,0.361767,-1.255651,0.000026,0.004771,GRCh38,Gene Expression,False
36599,36599,AC007325.4,ENSG00000278817,False,1.540291e-03,1.698493,0.659091,0.000672,0.029774,GRCh38,Gene Expression,False
36600,36600,AC007325.2,ENSG00000277196,False,5.988564e-04,1.381752,0.205388,0.000321,0.017708,GRCh38,Gene Expression,False

### Create anndata object/h5ad file from TileDB-SOMA experiment

**Create anndata object from TileDB-SOMA experiment**

In [6]:
experiment_path = "s3://rancho-scrna-live/tiledb-experiments/batch1/GSE123813/tiledbsoma_expt"
expt = soma.Experiment.open(experiment_path)

adata_from_expt = tiledbsoma.io.to_anndata(
    expt,
    measurement_name="RNA"
)

adata_from_expt

AnnData object with n_obs × n_vars = 102335 × 36601
    obs: 'orig.ident', 'nFeature_RNA', 'nCount_RNA', 'percent.mt', 'high_mt', 'high_ct', 'doublet_score', 'predicted_doublet', 'basic_qc', 'leiden', 'sample_id', 'author_cell_id', 'study_id', 'shortname', 'title', 'authors', 'pmid', 'doi', 'publication_date', 'study_description', 'repository', 'repository_identifier', 'repository_url', 'Celltypist_Cell_Annotation', 'Celltypist_Cell_Annotation_Conf_Score', 'scArches_Cell_Annotation', 'scArches_Cell_Annotation_Uncert', 'author_cell_type', 'author_cell_type_cell_ontology_id', 'author_cell_type_cell_ontology_name', 'scArches_Cell_Type_Ontology_ID', 'scArches_Cell_Type_Ontology_Name', 'Celltypist_Cell_Type_Ontology_Name', 'Celltypist_Cell_Type_Ontology_ID', 'sample_type', 'sample_name', 'sample_cell_line_accession_cellosaurus', 'sample_cell_line_name_cellosaurus', 'sample_tissue', 'sample_tissue_uberon_id', 'sample_tissue_uberon_name', 'sample_pathology', 'sample_treatment', 'sample_treatment_mesh', 'sample_treatment_dose', 'sample_treatment_dose_unit', 'sample_treatment_exposure_duration', 'sample_collection_time', 'sample_collection_time_unit', 'sample_biomarkers', 'sample_replicate', 'sample_group', 'sample_library_preparation_EFO_id', 'sample_library_preparation_EFO_name', 'sample_instrument', 'sample_reference_genome', 'sample_other_information', 'cell_batch', 'cell_technology_type', 'experiment_platform', 'library_selection', 'rna_integrity_number', 'technology_type', 'sample_disease', 'sample_disease_id', 'sample_treatment_substance', 'sample_treatment_substance_id', 'sample_treatment_timepoint', 'sample_collection_method', 'sample_in_vivo_harvest_timepoint', 'sample_preservation_method', 'sample_treatment_timepoint_unit', 'donor_id', 'donor_organism', 'donor_strain', 'donor_race', 'donor_sex', 'donor_age', 'donor_age_unit', 'donor_disease', 'donor_disease_doid_id', 'donor_disease_doid_name', 'donor_disease_duration', 'donor_other_illness', 'donor_treatment', 'donor_treatment_mesh', 'donor_treatment_dose', 'donor_treatment_dose_unit', 'donor_treatment_route', 'donor_treatment_dose_frequency', 'donor_treatment_response', 'donor_tumor_stage', 'donor_tumor_diagnosis_time', 'donor_tumor_diagnosis_time_unit', 'donor_cancer_type', 'donor_smoking_history', 'donor_alcohol_use_history', 'donor_study_group', 'development_stage_ontology_name', 'development_stage_ontology_term_id', 'donor_disease_mondo_id', 'donor_disease_mondo_name', 'donor_genotype', 'organism_ontology_term_id', 'organism_ontology_term_name', 'sex_ontology_term_id', 'donor_treatment_mesh_id', 'batch', 'collection', 'scds', 'dataset_data_type', 'curation_dataset_id', 'dataset_repository', 'dataset_repository_url', 'dataset_workflow', 'sample_number'
    var: 'gene_ids', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std', 'genome', 'feature_types', 'mt'
    uns: 'Celltypist', 'Celltypist_Cell_Type_Ontology_Name_colors', 'author_cell_type_cell_ontology_name_colors', 'author_cell_type_cell_ontology_name_order', 'hvg', 'leiden', 'leiden_colors', 'leiden_order', 'log1p', 'neighbors', 'orig.ident_colors', 'orig.ident_order', 'over_clustering', 'pca', 'scArches_Cell_Annotation_colors', 'scArches_Cell_Annotation_order', 'umap', 'shortname'
    obsm: 'X_pca', 'X_pca_harmony', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

**Create anndata h5ad file from TileDB-SOMA experiment**

`tiledbsoma.io.to_h5ad()` writes the file directly, but it fails when an `obs`/`var` column is entirely `None`/`NaN` — h5py can't serialize an all-null object column as an HDF5 string, raising:

```
TypeError: Can't implicitly convert non-string objects to strings
```

To avoid this, build the AnnData first, coerce object (string) columns to real strings (turning `None` into `""`), then write the h5ad.

In [7]:
experiment_path = "s3://rancho-scrna-live/tiledb-experiments/batch1/GSE123813/tiledbsoma_expt"
batch = experiment_path.rstrip("/").split("/")[-3]
dataset = experiment_path.rstrip("/").split("/")[-2]
h5ad_name = f"{batch}_{dataset}_anndata.h5ad"
h5ad_path = f"/tmp/{h5ad_name}"

expt = soma.Experiment.open(experiment_path)

# Build the AnnData, then coerce object columns to strings so all-None columns
# (e.g. study_institution) don't break the h5ad write.
adata = tiledbsoma.io.to_anndata(expt, measurement_name="RNA")

def stringify_object_columns(df):
    """Cast object-dtype columns to str, turning None/NaN into empty strings."""
    for col in df.columns:
        if df[col].dtype == object:
            df[col] = df[col].astype("string").fillna("").astype(str)

stringify_object_columns(adata.obs)
stringify_object_columns(adata.var)

adata.write_h5ad(h5ad_path)
print(f"Anndata from {experiment_path} is written to {h5ad_path}")

Anndata from s3://rancho-scrna-live/tiledb-experiments/batch1/GSE123813/tiledbsoma_expt is written to /tmp/batch1_GSE123813_anndata.h5ad

### Slicing and Filtering Experiments

**Querying for cells with nFeature_RNA > 1000 and genes that are highly_variable**

The query result object (`query`) allows to inspect the query result and selectively access the data instead of loading the entire dataset

In [8]:
query = soma.ExperimentAxisQuery(
    experiment=expt,
    measurement_name="RNA",
    obs_query=soma.AxisQuery(
        value_filter="nFeature_RNA > 1000",
    ),
    var_query=soma.AxisQuery(
        value_filter="highly_variable == True",
    ),
)

**See how many cells and genes are returned with the above query**

In [9]:

(query.n_obs, query.n_vars)

(93535, 2896)

**Access the DataFrame containing the annotations for all cells returned by the above query**

In [10]:
query.obs().concat().to_pandas()

,soma_joinid,obs_id,orig.ident,nFeature_RNA,nCount_RNA,percent.mt,high_mt,high_ct,doublet_score,predicted_doublet,...,donor_treatment_mesh_id,batch,collection,scds,dataset_data_type,curation_dataset_id,dataset_repository,dataset_repository_url,dataset_workflow,sample_number
0,0,GSM3721447_AAACCTGAGCGCCTCA-1,GSM3721447,1502,4678.0,1.859769,False,False,0.098627,False,...,NA,batch1,NA,True,GEX,GSE123813,NA,NA,cellranger_7,52
1,1,GSM3721447_AAACCTGAGGCAAAGA-1,GSM3721447,1156,2891.0,3.977862,False,False,0.093079,False,...,NA,batch1,NA,True,GEX,GSE123813,NA,NA,cellranger_7,52
2,2,GSM3721447_AAACCTGCAGACAAAT-1,GSM3721447,1712,5830.0,2.727273,False,False,0.051482,False,...,NA,batch1,NA,True,GEX,GSE123813,NA,NA,cellranger_7,52
3,3,GSM3721447_AAACCTGCATTCGACA-1,GSM3721447,1358,3972.0,3.172205,False,False,0.056291,False,...,NA,batch1,NA,True,GEX,GSE123813,NA,NA,cellranger_7,52
4,4,GSM3721447_AAACCTGGTCCCGACA-1,GSM3721447,2296,7875.0,3.085714,False,False,0.206497,False,...,NA,batch1,NA,True,GEX,GSE123813,NA,NA,cellranger_7,52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93530,102330,GSM3511746_TTCTTAGCATAAGACA-1,GSM3511746,4565,21899.0,2.675921,False,False,0.059406,False,...,NA,batch1,NA,True,GEX,GSE123813,NA,NA,cellranger_7,52
93531,102331,GSM3511746_TTGAACGAGTACTTGC-1,GSM3511746,4947,19979.0,4.089293,False,False,0.109375,False,...,NA,batch1,NA,True,GEX,GSE123813,NA,NA,cellranger_7,52
93532,102332,GSM3511746_TTGACTTTCCGTAGGC-1,GSM3511746,3797,18281.0,1.903616,False,False,0.059406,False,...,NA,batch1,NA,True,GEX,GSE123813,NA,NA,cellranger_7,52
93533,102333,GSM3511746_TTTACTGGTCGCGAAA-1,GSM3511746,4130,19409.0,2.266989,False,False,0.028754,False,...,NA,batch1,NA,True,GEX,GSE123813,NA,NA,cellranger_7,52
93534,102334,GSM3511746_TTTATGCAGATAGTCA-1,GSM3511746,3999,17188.0,2.117757,False,False,0.018088,False,...,NA,batch1,NA,True,GEX,GSE123813,NA,NA,cellranger_7,52

**Load the expression matrix (normalized counts) for the selected cells and genes as a Pandas DataFrame**

In [11]:
query.X(layer_name="data").tables().concat().to_pandas()

          soma_dim_0  soma_dim_1  soma_data
0                  0         429   1.143479
1                  0         597   2.256611
2                  0        1182   2.003235
3                  1        1182   1.494927
4                  1        1832   1.494927
...              ...         ...        ...
13156144      102334       36043   0.458564
13156145      102334       36094   0.771775
13156146      102334       36366   1.202133
13156147      102334       36371   0.458564
13156148      102334       36378   1.009928

[13156149 rows x 3 columns]

**Load the raw counts**

In [12]:
query.X(layer_name="counts").tables().concat().to_pandas()

          soma_dim_0  soma_dim_1  soma_data
0                  0         429        1.0
1                  0         597        4.0
2                  0        1182        3.0
3                  1        1182        1.0
4                  1        1832        1.0
...              ...         ...        ...
13156144      102334       36043        1.0
13156145      102334       36094        2.0
13156146      102334       36366        4.0
13156147      102334       36371        1.0
13156148      102334       36378        3.0

[13156149 rows x 3 columns]

**Querying for CD8+ T cells and genes that are highly_variable**

In [14]:
expt_uri = "s3://rancho-scrna-live/tiledb-experiments/batch1/GSE123813/tiledbsoma_expt"
expt = soma.Experiment.open(expt_uri)
print(expt)

query = soma.ExperimentAxisQuery(
    experiment=expt,
    measurement_name="RNA",
    obs_query=soma.AxisQuery(
        value_filter="scArches_Cell_Type_Ontology_Name == 'CD8-positive, alpha-beta T cell'",
    ),
    var_query=soma.AxisQuery(
        value_filter="highly_variable == True",
    ),
)

(query.n_obs, query.n_vars)

<Experiment 's3://rancho-scrna-live/tiledb-experiments/batch1/GSE123813/tiledbsoma_expt' (open for 'r') (2 items)
    'ms': 's3://rancho-scrna-live/tiledb-experiments/batch1/GSE123813/tiledbsoma_expt/ms' (unopened)
    'obs': 's3://rancho-scrna-live/tiledb-experiments/batch1/GSE123813/tiledbsoma_expt/obs' (unopened)>

(1077, 2896)

**Query result to anndata object**

In [15]:
adata_from_query = query.to_anndata(X_name="data")
adata_from_query

AnnData object with n_obs × n_vars = 1077 × 2896
    obs: 'soma_joinid', 'orig.ident', 'nFeature_RNA', 'nCount_RNA', 'percent.mt', 'high_mt', 'high_ct', 'doublet_score', 'predicted_doublet', 'basic_qc', 'leiden', 'sample_id', 'author_cell_id', 'study_id', 'shortname', 'title', 'authors', 'pmid', 'doi', 'publication_date', 'study_description', 'repository', 'repository_identifier', 'repository_url', 'Celltypist_Cell_Annotation', 'Celltypist_Cell_Annotation_Conf_Score', 'scArches_Cell_Annotation', 'scArches_Cell_Annotation_Uncert', 'author_cell_type', 'author_cell_type_cell_ontology_id', 'author_cell_type_cell_ontology_name', 'scArches_Cell_Type_Ontology_ID', 'scArches_Cell_Type_Ontology_Name', 'Celltypist_Cell_Type_Ontology_Name', 'Celltypist_Cell_Type_Ontology_ID', 'sample_type', 'sample_name', 'sample_cell_line_accession_cellosaurus', 'sample_cell_line_name_cellosaurus', 'sample_tissue', 'sample_tissue_uberon_id', 'sample_tissue_uberon_name', 'sample_pathology', 'sample_treatment', 'sample_treatment_mesh', 'sample_treatment_dose', 'sample_treatment_dose_unit', 'sample_treatment_exposure_duration', 'sample_collection_time', 'sample_collection_time_unit', 'sample_biomarkers', 'sample_replicate', 'sample_group', 'sample_library_preparation_EFO_id', 'sample_library_preparation_EFO_name', 'sample_instrument', 'sample_reference_genome', 'sample_other_information', 'cell_batch', 'cell_technology_type', 'experiment_platform', 'library_selection', 'rna_integrity_number', 'technology_type', 'sample_disease', 'sample_disease_id', 'sample_treatment_substance', 'sample_treatment_substance_id', 'sample_treatment_timepoint', 'sample_collection_method', 'sample_in_vivo_harvest_timepoint', 'sample_preservation_method', 'sample_treatment_timepoint_unit', 'donor_id', 'donor_organism', 'donor_strain', 'donor_race', 'donor_sex', 'donor_age', 'donor_age_unit', 'donor_disease', 'donor_disease_doid_id', 'donor_disease_doid_name', 'donor_disease_duration', 'donor_other_illness', 'donor_treatment', 'donor_treatment_mesh', 'donor_treatment_dose', 'donor_treatment_dose_unit', 'donor_treatment_route', 'donor_treatment_dose_frequency', 'donor_treatment_response', 'donor_tumor_stage', 'donor_tumor_diagnosis_time', 'donor_tumor_diagnosis_time_unit', 'donor_cancer_type', 'donor_smoking_history', 'donor_alcohol_use_history', 'donor_study_group', 'development_stage_ontology_name', 'development_stage_ontology_term_id', 'donor_disease_mondo_id', 'donor_disease_mondo_name', 'donor_genotype', 'organism_ontology_term_id', 'organism_ontology_term_name', 'sex_ontology_term_id', 'donor_treatment_mesh_id', 'batch', 'collection', 'scds', 'dataset_data_type', 'curation_dataset_id', 'dataset_repository', 'dataset_repository_url', 'dataset_workflow', 'sample_number'
    var: 'soma_joinid', 'gene_ids', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std', 'genome', 'feature_types', 'mt'

## Manifests

A **manifest** is a single Parquet file that indexes the cell-level metadata (`obs`) for *every* experiment in a collection. Instead of opening each experiment to inspect its annotations, you can load the manifest into a pandas DataFrame and query across the whole collection at once.

Each row is one cell. The columns are the union of every experiment's `obs` columns, plus four bookkeeping columns added by `tiledbsoma_manifest.py`:

- `experiment` — the source experiment the cell came from
- `collection_name` — the collection the experiment belongs to
- `n_cells` — total cells in that source experiment
- `n_genes` — number of genes (RNA `var`) in that source experiment

Manifests live under `s3://rancho-scrna-live/manifests/`, one per collection (e.g. `Human_10x_manifest.parquet`).

### List the available manifests

In [16]:
fs = s3fs.S3FileSystem()
manifests_base = "s3://rancho-scrna-live/manifests"

for path in fs.ls(manifests_base):
    if path.endswith(".parquet"):
        size_mb = fs.info(path)["size"] / 1e6
        print(f"{path.split('/')[-1]:35s} {size_mb:8.1f} MB")

Cynomolgus_10x_manifest.parquet         12.7 MB
Human_10x_manifest.parquet            1609.7 MB
Human_ss2_manifest.parquet               2.7 MB
Mouse_10x_manifest.parquet             429.3 MB
Mouse_ss2_manifest.parquet               0.6 MB
Rhesus_10x_manifest.parquet              7.7 MB

### Load a manifest

Read the Parquet file straight from S3 into a pandas DataFrame. (The larger manifests such as `Human_10x` are several hundred MB / >1 GB — start with a smaller one like `Human_ss2` to explore.)

In [17]:
manifest_uri = "s3://rancho-scrna-live/manifests/Human_ss2_manifest.parquet"
manifest = pd.read_parquet(manifest_uri)

print(f"{len(manifest):,} cells x {manifest.shape[1]} columns")
print(f"{manifest['experiment'].nunique()} experiments in collection "
      f"'{manifest['collection_name'].iloc[0]}'")
manifest.head()

66,641 cells x 121 columns
23 experiments in collection 'Human_ss2'

,obs_id,orig.ident,nFeature_RNA,nCount_RNA,percent.mt,high_mt,high_ct,predicted_doublet,doublet_score,basic_qc,...,scds,dataset_data_type,curation_dataset_id,dataset_repository,dataset_repository_url,dataset_workflow,experiment,collection_name,n_cells,n_genes
0,11511L&R_11511L-P4-B12,11511L&R,2402,1208875.0,5.110454,False,False,False,0.0,PASS,...,True,GEX,GSE132149,None,None,smartseq,batch10_GSE132149,Human_ss2,2711,36522
1,11511L&R_11511R-P1-C07,11511L&R,2457,1223564.0,6.849662,False,False,False,0.0,PASS,...,True,GEX,GSE132149,None,None,smartseq,batch10_GSE132149,Human_ss2,2711,36522
2,11511L&R_11511R-P1-C12,11511L&R,1819,1181745.0,6.639927,False,False,False,0.0,PASS,...,True,GEX,GSE132149,None,None,smartseq,batch10_GSE132149,Human_ss2,2711,36522
3,11511L&R_11511R-P1-A03,11511L&R,3195,1370480.0,6.610896,False,False,False,0.0,PASS,...,True,GEX,GSE132149,None,None,smartseq,batch10_GSE132149,Human_ss2,2711,36522
4,11511L&R_11511R-P3-G07,11511L&R,2862,1127385.0,8.559365,False,False,False,0.0,PASS,...,True,GEX,GSE132149,None,None,smartseq,batch10_GSE132149,Human_ss2,2711,36522

### See the available annotation columns

The manifest carries all of the per-cell metadata, including donor/sample fields, QC metrics, and the `popv_*` cell-type predictions.

In [18]:
list(manifest.columns)

['obs_id',
 'orig.ident',
 'nFeature_RNA',
 'nCount_RNA',
 'percent.mt',
 'high_mt',
 'high_ct',
 'predicted_doublet',
 'doublet_score',
 'basic_qc',
 'leiden',
 'sample_id',
 'author_cell_id',
 'study_id',
 'shortname',
 'title',
 'authors',
 'pmid',
 'doi',
 'publication_date',
 'study_description',
 'repository',
 'repository_identifier',
 'repository_url',
 'sample_number',
 'scArches_Cell_Annotation',
 'scArches_Cell_Annotation_Uncert',
 'Celltypist_Cell_Annotation',
 'Celltypist_Cell_Annotation_Conf_Score',
 'author_cell_type',
 'author_cell_type_cell_ontology_id',
 'author_cell_type_cell_ontology_name',
 'scArches_Cell_Type_Ontology_ID',
 'scArches_Cell_Type_Ontology_Name',
 'Celltypist_Cell_Type_Ontology_Name',
 'Celltypist_Cell_Type_Ontology_ID',
 'sample_type',
 'sample_name',
 'sample_cell_line_accession_cellosaurus',
 'sample_cell_line_name_cellosaurus',
 'sample_tissue',
 'sample_tissue_uberon_id',
 'sample_tissue_uberon_name',
 'sample_pathology',
 'sample_treatment',
 'sample_treatment_mesh',
 'sample_treatment_dose',
 'sample_treatment_dose_unit',
 'sample_treatment_exposure_duration',
 'sample_collection_time',
 'sample_collection_time_unit',
 'sample_biomarkers',
 'sample_replicate',
 'sample_group',
 'sample_library_preparation_EFO_id',
 'sample_library_preparation_EFO_name',
 'sample_instrument',
 'sample_reference_genome',
 'sample_other_information',
 'cell_batch',
 'cell_technology_type',
 'experiment_platform',
 'library_selection',
 'rna_integrity_number',
 'technology_type',
 'sample_disease',
 'sample_disease_id',
 'sample_treatment_substance',
 'sample_treatment_substance_id',
 'sample_treatment_timepoint',
 'sample_collection_method',
 'sample_in_vivo_harvest_timepoint',
 'sample_preservation_method',
 'sample_treatment_timepoint_unit',
 'donor_id',
 'donor_organism',
 'donor_strain',
 'donor_race',
 'donor_sex',
 'donor_age',
 'donor_age_unit',
 'donor_disease',
 'donor_disease_doid_id',
 'donor_disease_doid_name',
 'donor_disease_duration',
 'donor_other_illness',
 'donor_treatment',
 'donor_treatment_mesh',
 'donor_treatment_dose',
 'donor_treatment_dose_unit',
 'donor_treatment_route',
 'donor_treatment_dose_frequency',
 'donor_treatment_response',
 'donor_tumor_stage',
 'donor_tumor_diagnosis_time',
 'donor_tumor_diagnosis_time_unit',
 'donor_cancer_type',
 'donor_smoking_history',
 'donor_alcohol_use_history',
 'donor_study_group',
 'development_stage_ontology_name',
 'development_stage_ontology_term_id',
 'donor_disease_mondo_id',
 'donor_disease_mondo_name',
 'donor_genotype',
 'organism_ontology_term_id',
 'organism_ontology_term_name',
 'sex_ontology_term_id',
 'donor_treatment_mesh_id',
 'batch',
 'collection',
 'scds',
 'dataset_data_type',
 'curation_dataset_id',
 'dataset_repository',
 'dataset_repository_url',
 'dataset_workflow',
 'experiment',
 'collection_name',
 'n_cells',
 'n_genes']

### Per-experiment summary

`n_cells` and `n_genes` are constant within an experiment, so drop duplicates to get a quick overview of what's in the collection.

In [19]:
(manifest[["experiment", "n_cells", "n_genes"]]
    .drop_duplicates()
    .sort_values("n_cells", ascending=False)
    .reset_index(drop=True))

                     experiment  n_cells  n_genes
0           batch12_PRJNA591860    20056    36522
1             batch7_PRJEB14362    17264    36522
2             batch13_GSE151091     6394    36522
3              batch7_GSE133707     5957    36522
4               batch5_GSE84465     3134    36601
5              batch9_GSE182870     2840    36522
6             batch10_GSE132149     2711    36522
7              batch7_GSE178209     1908    36522
8             batch10_GSE225331     1010    36522
9             batch10_GSE139079      998    36522
10              batch8_GSE57872      756    36522
11           batch8_PRJNA379992      662    36522
12             batch8_GSE118900      534    36522
13             batch10_GSE86618      470    36522
14            batch12_GSE154906      388    36522
15        batch12_GSE150672_ss2      362    36522
16              batch7_GSE95459      283    36522
17            batch13_GSE138302      241    36522
18            batch12_GSE145844      164    36522
19           batch6_E-MTAB-7303      162    36522
20  batch13_GSE243750_human_ss2      151    36522
21            batch12_GSE145825      121    36522
22            batch12_GSE146323       75    36522

### Explore an annotation column across the whole collection

Because the manifest aggregates every experiment, a single `value_counts()` summarizes the entire collection. Here we look at the consensus cell-type prediction and the tissue of origin.

In [21]:
print("Predicted cell types (popv majority vote):")
print(manifest["scArches_Cell_Type_Ontology_Name"].value_counts().head(15))

print("\nTissues:")
print(manifest["sample_tissue_uberon_name"].value_counts().head(15))

Predicted cell types (popv majority vote):
scArches_Cell_Type_Ontology_Name
embryonic stem cell                       17264
macrophage                                 4943
melanocyte                                 4641
T cell                                     4349
epithelial cell                            4215
retinal rod cell                           4081
fibroblast                                 3000
secretory cell                             2854
CD4-positive, alpha-beta memory T cell     2768
plasma cell                                1717
dendritic cell                             1713
keratinocyte                               1677
malignant cell                             1535
endothelial cell                           1090
basal cell                                  929
Name: count, dtype: int64

Tissues:
sample_tissue_uberon_name
endoderm                                                          17264
lung                                                              10532
lymph node                                                         4754
macula lutea                                                       4618
blood                                                              3910
brain                                                              3807
fallopian tube                                                     3709
liver                                                              3399
pleura                                                             2915
skin of palm of manus|skin of leg|skin of sole of pes              1349
peripheral region of retina                                        1339
upper leg skin                                                      886
arm skin                                                            860
skin of pes|skin of calf|heel skin|skin of shin                     845
arm skin|skin of palm of manus|skin of leg|skin of sole of pes      674
Name: count, dtype: int64

### Cross-tabulate: which experiments contain which cell types

A `groupby` / `crosstab` tells you where a given cell population lives *before* you open any experiment.

In [22]:
cell_type = "T cell"

hits = manifest[manifest["scArches_Cell_Type_Ontology_Name"] == cell_type]
print(f"{len(hits):,} '{cell_type}' cells across "
      f"{hits['experiment'].nunique()} experiments\n")
print(hits["experiment"].value_counts())

4,349 'T cell' cells across 3 experiments

experiment
batch12_PRJNA591860    4342
batch8_PRJNA379992        4
batch13_GSE151091         3
Name: count, dtype: int64

### Filter across experiments

Combine any conditions to build a cohort spanning the whole collection — e.g. T cells with more than 1,000 detected genes.

In [23]:
subset = manifest[
    (manifest["scArches_Cell_Type_Ontology_Name"] == "T cell")
    & (manifest["nFeature_RNA"] > 1000)
]

print(f"{len(subset):,} cells matched, from experiments: "
      f"{sorted(subset['experiment'].unique())}")
subset[["experiment", "obs_id", "nFeature_RNA", "nCount_RNA",
        "sample_tissue_uberon_name", "scArches_Cell_Type_Ontology_Name"]].head()

4,135 cells matched, from experiments: ['batch12_PRJNA591860', 'batch13_GSE151091', 'batch8_PRJNA379992']

,experiment,obs_id,nFeature_RNA,nCount_RNA,sample_tissue_uberon_name,scArches_Cell_Type_Ontology_Name
6300,batch12_PRJNA591860,AZ_01_C16_B001546,1766,5.299300e+05,lung,T cell
6303,batch12_PRJNA591860,AZ_01_C13_B001544,3862,1.016561e+06,lung,T cell
6304,batch12_PRJNA591860,AZ_01_E16_B001546,2583,8.085520e+05,lung,T cell
6305,batch12_PRJNA591860,AZ_01_C19_B001544,1726,2.560750e+05,lung,T cell
6314,batch12_PRJNA591860,AZ_01_B18_B001544,3686,5.638610e+05,lung,T cell

### Use the manifest to decide which experiments to open

A common pattern: query the manifest to find the experiments worth loading, then open just those from the collection to pull expression data. This avoids scanning experiments that contain nothing of interest.

In [24]:
collection_name = manifest["collection_name"].iloc[0]
collection_uri = f"s3://rancho-scrna-live/collections/{collection_name}"

# Experiments in this collection that contain the cell type of interest
experiments_of_interest = sorted(
    manifest.loc[manifest["scArches_Cell_Type_Ontology_Name"] == "T cell", "experiment"].unique()
)
print("Experiments to open:", experiments_of_interest)

with soma.Collection.open(collection_uri) as collection:
    for expt_name in experiments_of_interest:
        expt = collection[expt_name]
        query = soma.ExperimentAxisQuery(
            experiment=expt,
            measurement_name="RNA",
            obs_query=soma.AxisQuery(
                value_filter="scArches_Cell_Type_Ontology_Name == 'T cell'"
            ),
        )
        print(f"{expt_name}: {query.n_obs:,} cells x {query.n_vars:,} genes")

Experiments to open: ['batch12_PRJNA591860', 'batch13_GSE151091', 'batch8_PRJNA379992']
batch12_PRJNA591860: 4,342 cells x 36,522 genes
batch13_GSE151091: 3 cells x 36,522 genes
batch8_PRJNA379992: 4 cells x 36,522 genes

## Collections

### List collections in the tiledbsoma_collections directory

In [25]:
fs = s3fs.S3FileSystem()
collections_base = "s3://rancho-scrna-live/collections"
collection_names = [p.split("/")[-1] for p in fs.ls(collections_base)]

for i, name in enumerate(collection_names, start=1):
    collection_uri = f"{collections_base}/{name}"
    try:
        with soma.Collection.open(collection_uri) as collection:
            print(f"{i}. {name}")
    except Exception:
        continue

1. Cynomolgus_10x
2. Human_10x
3. Human_ss2
4. Mouse_10x
5. Mouse_ss2
6. Rhesus_10x

### List experiments available in each collection

In [26]:
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', None)

fs = s3fs.S3FileSystem()
collections_base = "s3://rancho-scrna-live/collections"
collection_names = [p.split("/")[-1] for p in fs.ls(collections_base)]
experiments = []

for name in collection_names:
    collection_uri = f"{collections_base}/{name}"
    try:
        with soma.Collection.open(collection_uri) as collection:
            for key in collection.keys():
                obj = collection[key]
                if isinstance(obj, soma.Experiment):
                    experiments.append(
                        {
                            "Collection Name": name,
                            "Experiment": key,
                            "Experiment URI": obj.uri,
                        }
                    )
    except Exception:
        continue

experiments = pd.DataFrame(experiments)
print(experiments.to_string(index=False))

Collection Name                                   Experiment                                                                                         Experiment URI
 Cynomolgus_10x                             batch9_CRA002577                             s3://rancho-scrna-live/tiledb-experiments/batch9/CRA002577/tiledbsoma_expt
 Cynomolgus_10x                             batch9_CRA002689                             s3://rancho-scrna-live/tiledb-experiments/batch9/CRA002689/tiledbsoma_expt
 Cynomolgus_10x                             batch9_GSE196792                             s3://rancho-scrna-live/tiledb-experiments/batch9/GSE196792/tiledbsoma_expt
      Human_10x                         batch10_E-MTAB-12339                         s3://rancho-scrna-live/tiledb-experiments/batch10/E-MTAB-12339/tiledbsoma_expt
      Human_10x                         batch10_E-MTAB-13664                         s3://rancho-scrna-live/tiledb-experiments/batch10/E-MTAB-13664/tiledbsoma_expt
      Human_10x                            batch10_GSE112271                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE112271/tiledbsoma_expt
      Human_10x                      batch10_GSE126836_human                      s3://rancho-scrna-live/tiledb-experiments/batch10/GSE126836_human/tiledbsoma_expt
      Human_10x                            batch10_GSE136035                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE136035/tiledbsoma_expt
      Human_10x                            batch10_GSE137829                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE137829/tiledbsoma_expt
      Human_10x                            batch10_GSE141578                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE141578/tiledbsoma_expt
      Human_10x                            batch10_GSE143706                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE143706/tiledbsoma_expt
      Human_10x                            batch10_GSE148434                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE148434/tiledbsoma_expt
      Human_10x                            batch10_GSE150290                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE150290/tiledbsoma_expt
      Human_10x                            batch10_GSE153765                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE153765/tiledbsoma_expt
      Human_10x                            batch10_GSE161192                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE161192/tiledbsoma_expt
      Human_10x                            batch10_GSE163558                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE163558/tiledbsoma_expt
      Human_10x                            batch10_GSE164690                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE164690/tiledbsoma_expt
      Human_10x                            batch10_GSE168668                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE168668/tiledbsoma_expt
      Human_10x                            batch10_GSE168933                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE168933/tiledbsoma_expt
      Human_10x                            batch10_GSE170673                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE170673/tiledbsoma_expt
      Human_10x                            batch10_GSE173468                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE173468/tiledbsoma_expt
      Human_10x                            batch10_GSE176160                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE176160/tiledbsoma_expt
      Human_10x                            batch10_GSE180122                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE180122/tiledbsoma_expt
      Human_10x                      batch10_GSE186538_human                      s3://rancho-scrna-live/tiledb-experiments/batch10/GSE186538_human/tiledbsoma_expt
      Human_10x                            batch10_GSE188737                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE188737/tiledbsoma_expt
      Human_10x                            batch10_GSE189040                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE189040/tiledbsoma_expt
      Human_10x                            batch10_GSE189754                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE189754/tiledbsoma_expt
      Human_10x                            batch10_GSE190564                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE190564/tiledbsoma_expt
      Human_10x                            batch10_GSE193337                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE193337/tiledbsoma_expt
      Human_10x                            batch10_GSE193688                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE193688/tiledbsoma_expt
      Human_10x                            batch10_GSE194245                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE194245/tiledbsoma_expt
      Human_10x                            batch10_GSE196936                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE196936/tiledbsoma_expt
      Human_10x                            batch10_GSE197677                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE197677/tiledbsoma_expt
      Human_10x                            batch10_GSE202601                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE202601/tiledbsoma_expt
      Human_10x                            batch10_GSE205049                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE205049/tiledbsoma_expt
      Human_10x                            batch10_GSE205589                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE205589/tiledbsoma_expt
      Human_10x                            batch10_GSE210038                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE210038/tiledbsoma_expt
      Human_10x                            batch10_GSE210679                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE210679/tiledbsoma_expt
      Human_10x                            batch10_GSE212109                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE212109/tiledbsoma_expt
      Human_10x                            batch10_GSE213569                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE213569/tiledbsoma_expt
      Human_10x                            batch10_GSE213740                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE213740/tiledbsoma_expt
      Human_10x                            batch10_GSE220116                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE220116/tiledbsoma_expt
      Human_10x                            batch10_GSE223178                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE223178/tiledbsoma_expt
      Human_10x                            batch10_GSE225170                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE225170/tiledbsoma_expt
      Human_10x                            batch10_GSE226077                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE226077/tiledbsoma_expt
      Human_10x                            batch10_GSE226427                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE226427/tiledbsoma_expt
      Human_10x                            batch10_GSE227136                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE227136/tiledbsoma_expt
      Human_10x                            batch10_GSE228165                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE228165/tiledbsoma_expt
      Human_10x                            batch10_GSE231540                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE231540/tiledbsoma_expt
      Human_10x                            batch10_GSE235663                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE235663/tiledbsoma_expt
      Human_10x                            batch10_GSE237254                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE237254/tiledbsoma_expt
      Human_10x                            batch10_GSE242086                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE242086/tiledbsoma_expt
      Human_10x                            batch10_GSE243076                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE243076/tiledbsoma_expt
      Human_10x                            batch10_GSE243639                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE243639/tiledbsoma_expt
      Human_10x                            batch10_GSE244267                            s3://rancho-scrna-live/tiledb-experiments/batch10/GSE244267/tiledbsoma_expt
      Human_10x                          batch10_PRJNA679848                          s3://rancho-scrna-live/tiledb-experiments/batch10/PRJNA679848/tiledbsoma_expt
      Human_10x                          batch10_PRJNA726991                          s3://rancho-scrna-live/tiledb-experiments/batch10/PRJNA726991/tiledbsoma_expt
      Human_10x                          batch10_PRJNA916657                          s3://rancho-scrna-live/tiledb-experiments/batch10/PRJNA916657/tiledbsoma_expt
      Human_10x                            batch10_SRP403458                            s3://rancho-scrna-live/tiledb-experiments/batch10/SRP403458/tiledbsoma_expt
      Human_10x                    batch10_dat-717krsa_human                    s3://rancho-scrna-live/tiledb-experiments/batch10/dat-717krsa_human/tiledbsoma_expt
      Human_10x                            batch11_GSE130157                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE130157/tiledbsoma_expt
      Human_10x                            batch11_GSE132914                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE132914/tiledbsoma_expt
      Human_10x                            batch11_GSE138693                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE138693/tiledbsoma_expt
      Human_10x                      batch11_GSE142637_human                      s3://rancho-scrna-live/tiledb-experiments/batch11/GSE142637_human/tiledbsoma_expt
      Human_10x                      batch11_GSE143791_human                      s3://rancho-scrna-live/tiledb-experiments/batch11/GSE143791_human/tiledbsoma_expt
      Human_10x                            batch11_GSE146981                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE146981/tiledbsoma_expt
      Human_10x                            batch11_GSE164564                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE164564/tiledbsoma_expt
      Human_10x                            batch11_GSE178245                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE178245/tiledbsoma_expt
      Human_10x                            batch11_GSE182527                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE182527/tiledbsoma_expt
      Human_10x                            batch11_GSE185834                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE185834/tiledbsoma_expt
      Human_10x                            batch11_GSE185991                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE185991/tiledbsoma_expt
      Human_10x                            batch11_GSE189519                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE189519/tiledbsoma_expt
      Human_10x                            batch11_GSE190559                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE190559/tiledbsoma_expt
      Human_10x                            batch11_GSE193304                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE193304/tiledbsoma_expt
      Human_10x                            batch11_GSE199994                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE199994/tiledbsoma_expt
      Human_10x                            batch11_GSE207935                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE207935/tiledbsoma_expt
      Human_10x                            batch11_GSE210963                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE210963/tiledbsoma_expt
      Human_10x                      batch11_GSE212837_human                      s3://rancho-scrna-live/tiledb-experiments/batch11/GSE212837_human/tiledbsoma_expt
      Human_10x                            batch11_GSE212966                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE212966/tiledbsoma_expt
      Human_10x                            batch11_GSE213902                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE213902/tiledbsoma_expt
      Human_10x                            batch11_GSE218985                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE218985/tiledbsoma_expt
      Human_10x                            batch11_GSE222649                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE222649/tiledbsoma_expt
      Human_10x                            batch11_GSE226225                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE226225/tiledbsoma_expt
      Human_10x                            batch11_GSE231993                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE231993/tiledbsoma_expt
      Human_10x                            batch11_GSE233280                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE233280/tiledbsoma_expt
      Human_10x                            batch11_GSE233405                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE233405/tiledbsoma_expt
      Human_10x                            batch11_GSE233844                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE233844/tiledbsoma_expt
      Human_10x                            batch11_GSE233917                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE233917/tiledbsoma_expt
      Human_10x                            batch11_GSE234790                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE234790/tiledbsoma_expt
      Human_10x                            batch11_GSE235168                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE235168/tiledbsoma_expt
      Human_10x                            batch11_GSE244781                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE244781/tiledbsoma_expt
      Human_10x                            batch11_GSE249279                            s3://rancho-scrna-live/tiledb-experiments/batch11/GSE249279/tiledbsoma_expt
      Human_10x                            batch11_HRA000704                            s3://rancho-scrna-live/tiledb-experiments/batch11/HRA000704/tiledbsoma_expt
      Human_10x                         batch12_E-MTAB-11188                         s3://rancho-scrna-live/tiledb-experiments/batch12/E-MTAB-11188/tiledbsoma_expt
      Human_10x                         batch12_E-MTAB-11792                         s3://rancho-scrna-live/tiledb-experiments/batch12/E-MTAB-11792/tiledbsoma_expt
      Human_10x                            batch12_GSE119212                            s3://rancho-scrna-live/tiledb-experiments/batch12/GSE119212/tiledbsoma_expt
      Human_10x                            batch12_GSE130105                            s3://rancho-scrna-live/tiledb-experiments/batch12/GSE130105/tiledbsoma_expt
      Human_10x                      batch12_GSE145095_human                      s3://rancho-scrna-live/tiledb-experiments/batch12/GSE145095_human/tiledbsoma_expt
      Human_10x                            batch12_GSE145154                            s3://rancho-scrna-live/tiledb-experiments/batch12/GSE145154/tiledbsoma_expt
      Human_10x                        batch12_GSE150672_10x                        s3://rancho-scrna-live/tiledb-experiments/batch12/GSE150672_10x/tiledbsoma_expt
      Human_10x                            batch12_GSE155488                            s3://rancho-scrna-live/tiledb-experiments/batch12/GSE155488/tiledbsoma_expt
      Human_10x                      batch12_GSE156905_human                      s3://rancho-scrna-live/tiledb-experiments/batch12/GSE156905_human/tiledbsoma_expt
      Human_10x                            batch12_GSE161470                            s3://rancho-scrna-live/tiledb-experiments/batch12/GSE161470/tiledbsoma_expt
      Human_10x                            batch12_GSE163005                            s3://rancho-scrna-live/tiledb-experiments/batch12/GSE163005/tiledbsoma_expt
      Human_10x                            batch12_GSE163973                            s3://rancho-scrna-live/tiledb-experiments/batch12/GSE163973/tiledbsoma_expt
      Human_10x                            batch12_GSE174232                            s3://rancho-scrna-live/tiledb-experiments/batch12/GSE174232/tiledbsoma_expt
      Human_10x                            batch12_GSE176029                            s3://rancho-scrna-live/tiledb-experiments/batch12/GSE176029/tiledbsoma_expt
      Human_10x                            batch12_GSE178317                            s3://rancho-scrna-live/tiledb-experiments/batch12/GSE178317/tiledbsoma_expt
      Human_10x                            batch12_GSE178481                            s3://rancho-scrna-live/tiledb-experiments/batch12/GSE178481/tiledbsoma_expt
      Human_10x                            batch12_GSE180928                            s3://rancho-scrna-live/tiledb-experiments/batch12/GSE180928/tiledbsoma_expt
      Human_10x                            batch12_GSE186476                            s3://rancho-scrna-live/tiledb-experiments/batch12/GSE186476/tiledbsoma_expt
      Human_10x                            batch12_GSE187877                            s3://rancho-scrna-live/tiledb-experiments/batch12/GSE187877/tiledbsoma_expt
      Human_10x                            batch12_GSE191301                            s3://rancho-scrna-live/tiledb-experiments/batch12/GSE191301/tiledbsoma_expt
      Human_10x                            batch12_GSE193102                            s3://rancho-scrna-live/tiledb-experiments/batch12/GSE193102/tiledbsoma_expt
      Human_10x                            batch12_GSE193181                            s3://rancho-scrna-live/tiledb-experiments/batch12/GSE193181/tiledbsoma_expt
      Human_10x                            batch12_GSE195832                            s3://rancho-scrna-live/tiledb-experiments/batch12/GSE195832/tiledbsoma_expt
      Human_10x                            batch12_GSE199013                            s3://rancho-scrna-live/tiledb-experiments/batch12/GSE199013/tiledbsoma_expt
      Human_10x                            batch12_GSE199711                            s3://rancho-scrna-live/tiledb-experiments/batch12/GSE199711/tiledbsoma_expt
      Human_10x                            batch12_GSE200253                            s3://rancho-scrna-live/tiledb-experiments/batch12/GSE200253/tiledbsoma_expt
      Human_10x                            batch12_GSE201348                            s3://rancho-scrna-live/tiledb-experiments/batch12/GSE201348/tiledbsoma_expt

### Get the number of cells and genes in each experiment in the collections

In [27]:
def summarize_collection(collection_uri, measurement_name="RNA"):
    rows = []
    total_cells = 0

    with soma.Collection.open(collection_uri) as collection:
        for name, expt in collection.items():
            try:
                n_cells = expt.obs.count
                n_genes = expt.ms[measurement_name].var.count

                total_cells += n_cells
                rows.append((name, n_cells, n_genes))

            except Exception as e:
                rows.append((name, f"ERROR: {e}", None))

    df = pd.DataFrame(rows, columns=["experiment", "n_cells", "n_genes"])
    df.index = range(1, len(df) + 1)

    return df, total_cells

collections_base = "s3://rancho-scrna-live/collections"
collections = ["Human_10x", "Human_ss2", "Mouse_10x", "Mouse_ss2"]

for collection in collections:
    print(f"\nCollection: {collection}")
    df, total_cells = summarize_collection(f"{collections_base}/{collection}")
    print(df)
    print(f"Total cells in collection: {total_cells:,}")

Collection: Human_10x
                  experiment  n_cells  n_genes
1       batch10_E-MTAB-12339   133603    36601
2       batch10_E-MTAB-13664   993866    36601
3          batch10_GSE112271    43124    36601
4    batch10_GSE126836_human    80307    36601
5          batch10_GSE136035    24643    36601
..                       ...      ...      ...
529         batch9_GSE249622    87603    36601
530         batch9_GSE249793   135151    36601
531       batch9_PRJNA434002   109543    36601
532       batch9_PRJNA772047     6272    36601
533       batch9_PRJNA932556    35975    36601

[533 rows x 3 columns]
Total cells in collection: 43,773,974

Collection: Human_ss2
                     experiment  n_cells  n_genes
1             batch10_GSE132149     2711    36522
2             batch10_GSE139079      998    36522
3             batch10_GSE225331     1010    36522
4              batch10_GSE86618      470    36522
5             batch12_GSE145825      121    36522
6             batch12_GSE145844      164    36522
7             batch12_GSE146323       75    36522
8         batch12_GSE150672_ss2      362    36522
9             batch12_GSE154906      388    36522
10          batch12_PRJNA591860    20056    36522
11            batch13_GSE138302      241    36522
12            batch13_GSE151091     6394    36522
13  batch13_GSE243750_human_ss2      151    36522
14              batch5_GSE84465     3134    36601
15           batch6_E-MTAB-7303      162    36522
16             batch7_GSE133707     5957    36522
17             batch7_GSE178209     1908    36522
18              batch7_GSE95459      283    36522
19            batch7_PRJEB14362    17264    36522
20             batch8_GSE118900      534    36522
21              batch8_GSE57872      756    36522
22           batch8_PRJNA379992      662    36522
23             batch9_GSE182870     2840    36522
Total cells in collection: 66,641

Collection: Mouse_10x
                  experiment  n_cells  n_genes
1          batch10_CRA010641   685415    32285
2    batch10_GSE126836_mouse   157397    32285
3          batch10_GSE150742     9114    32285
4          batch10_GSE164674    32872    32285
5          batch10_GSE175546    80838    32285
..                       ...      ...      ...
198         batch9_GSE228232   101073    32285
199         batch9_GSE228233    53556    32285
200         batch9_GSE228629    17657    32285
201         batch9_GSE228981    22575    32285
202       batch9_PRJNA771932    25853    32285

[202 rows x 3 columns]
Total cells in collection: 12,467,871

Collection: Mouse_ss2
                 experiment  n_cells  n_genes
1         batch11_GSE108020      420    31992
2         batch11_GSE160048      545    31992
3         batch11_GSE174265      776    31992
4         batch11_GSE264553     2366    31992
5         batch12_GSE113973     1812    31992
6         batch12_GSE127235      832    31992
7     batch12_GSE140023_ss2      523    31992
8          batch12_GSE99701       81    31992
9         batch13_GSE146988      504    31992
10  batch13_GSE243750_mouse       98    31992
11         batch8_GSE144528     1835    31992
12     batch8_GSE182028_SS2     1769    31992
13         batch8_GSE209841      324    31992
14        batch8_PRJDB10888      259    31992
15     batch9_GSE122871_SS2      191    31992
Total cells in collection: 12,335

### Query on multiple experiments in a collection and create a combined anndata object

**Querying for specific type of cells (e.g., "T cell") in the experiments in Mouse_10x collection**

Run the below cell to define the function and then execute the code in the cell below it to query for a specific cell type across all experiments in the collection and combine results into a single Anndata object.

In [28]:
import anndata as ad

def query_cell_type_in_collection(collection, cell_type_to_query):
    collection_path = "s3://rancho-scrna-live/collections/" + collection
    collection = soma.Collection.open(collection_path)
    adatas = []

    for name, expt in collection.items():
        obs_df = expt.obs.read().concat().to_pandas()
        cell_type_labels = obs_df["scArches_Cell_Type_Ontology_Name"][(
            obs_df["scArches_Cell_Type_Ontology_Name"]
            .str.contains(cell_type_to_query, na=False)
        )].unique()

        print(f'Dataset {name} \n - Cell types based on query "{cell_type_to_query}": {list(cell_type_labels)}')

        if len(cell_type_labels) > 0:

            with expt.axis_query(
                measurement_name="RNA",
                obs_query=soma.AxisQuery(
                    value_filter=f"scArches_Cell_Type_Ontology_Name in {list(cell_type_labels)}"
                )
            ) as query:
                print(f' - n_obs, n_vars: {query.n_obs} cells, {query.n_vars} vars\n')
                adata = query.to_anndata(X_name="data")
                adata.obs["source_experiment"] = name
                adatas.append(adata)

    combined_adata = ad.concat(adatas, join="outer", label="experiment")
    return combined_adata

Run the below cell to query for a specific cell type across all experiments in the collection and combine results into a single Anndata object. You can update the collection and the cell type you want to query for as needed.

In [29]:
collection = 'Mouse_10x'
cell_type_to_query = 'T cell'
combined_adata = query_cell_type_in_collection(collection, cell_type_to_query)
combined_adata

Dataset batch10_CRA010641
 - Cell types based on query "T cell": ['mature NK T cell', 'CD4-positive, alpha-beta T cell', 'T cell', 'CD8-positive, alpha-beta T cell', 'regulatory T cell', 'naive T cell']
 - n_obs, n_vars: 36640 cells, 32285 vars

Dataset batch10_GSE126836_mouse
 - Cell types based on query "T cell": []
Dataset batch10_GSE150742
 - Cell types based on query "T cell": ['T cell', 'mature NK T cell', 'CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell', 'regulatory T cell']
 - n_obs, n_vars: 1989 cells, 32285 vars

Dataset batch10_GSE164674
 - Cell types based on query "T cell": []
Dataset batch10_GSE175546
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'T cell', 'mature NK T cell']
 - n_obs, n_vars: 1483 cells, 32285 vars

Dataset batch10_GSE179501
 - Cell types based on query "T cell": ['mature NK T cell', 'CD4-positive, alpha-beta T cell', 'T cell', 'CD8-positive, alpha-beta T cell', 'regulatory T cell']
 - n_obs, n_vars: 5288 cells, 32285 vars

Dataset batch10_GSE179502
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 1 cells, 32285 vars

Dataset batch10_GSE198422
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 24892 cells, 32285 vars

Dataset batch10_GSE200366
 - Cell types based on query "T cell": []
Dataset batch10_GSE206835
 - Cell types based on query "T cell": ['mature alpha-beta T cell', 'CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 25708 cells, 32285 vars

Dataset batch10_GSE208152
 - Cell types based on query "T cell": []
Dataset batch10_GSE224688
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 1661 cells, 32285 vars

Dataset batch10_GSE230145
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 8 cells, 32285 vars

Dataset batch10_GSE235664
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta memory T cell', 'regulatory T cell', 'gamma-delta T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell', 'naive thymus-derived CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 24455 cells, 32285 vars

Dataset batch10_GSE235741
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta T cell', 'T cell', 'CD8-positive, alpha-beta T cell', 'regulatory T cell', 'naive T cell']
 - n_obs, n_vars: 1427 cells, 32285 vars

Dataset batch10_GSE244269
 - Cell types based on query "T cell": ['effector CD8-positive, alpha-beta T cell', 'T cell', 'mature NK T cell', 'effector CD4-positive, alpha-beta T cell', 'regulatory T cell']
 - n_obs, n_vars: 34269 cells, 32285 vars

Dataset batch10_GSE249412
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 120 cells, 32285 vars

Dataset batch10_GSE264530
 - Cell types based on query "T cell": ['naive thymus-derived CD8-positive, alpha-beta T cell', 'gamma-delta T cell', 'regulatory T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 10039 cells, 32285 vars

Dataset batch10_dat-717krsa_mouse
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'T cell', 'mature NK T cell']
 - n_obs, n_vars: 182 cells, 32285 vars

Dataset batch11_CNP0000892
 - Cell types based on query "T cell": []
Dataset batch11_GSE132910
 - Cell types based on query "T cell": []
Dataset batch11_GSE142637_mouse
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 5451 cells, 32285 vars

Dataset batch11_GSE143791_mouse
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 22548 cells, 32285 vars

Dataset batch11_GSE150178
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 3479 cells, 32285 vars

Dataset batch11_GSE154718
 - Cell types based on query "T cell": []
Dataset batch11_GSE161340
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'T cell']
 - n_obs, n_vars: 78 cells, 32285 vars

Dataset batch11_GSE169531
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 2 cells, 32285 vars

Dataset batch11_GSE181333
 - Cell types based on query "T cell": ['mature NK T cell', 'CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell', 'T cell']
 - n_obs, n_vars: 157 cells, 32285 vars

Dataset batch11_GSE189307
 - Cell types based on query "T cell": []
Dataset batch11_GSE191246
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 17748 cells, 32285 vars

Dataset batch11_GSE199880
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 1029 cells, 32285 vars

Dataset batch11_GSE205982
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 1 cells, 32285 vars

Dataset batch11_GSE209912
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'T cell']
 - n_obs, n_vars: 142 cells, 32285 vars

Dataset batch11_GSE210286
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 360 cells, 32285 vars

Dataset batch11_GSE210719
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 28877 cells, 32285 vars

Dataset batch11_GSE212837_mouse
 - Cell types based on query "T cell": []
Dataset batch11_GSE215070
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 3679 cells, 32285 vars

Dataset batch11_GSE216836
 - Cell types based on query "T cell": ['mature NK T cell', 'T cell', 'CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 9465 cells, 32285 vars

Dataset batch11_GSE216848
 - Cell types based on query "T cell": []
Dataset batch11_GSE220466
 - Cell types based on query "T cell": ['mature alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 1678 cells, 32285 vars

Dataset batch11_GSE223394
 - Cell types based on query "T cell": ['T cell', 'CD8-positive, alpha-beta T cell', 'mature NK T cell']
 - n_obs, n_vars: 16 cells, 32285 vars

Dataset batch11_GSE224398
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'mature NK T cell', 'T cell']
 - n_obs, n_vars: 139 cells, 32285 vars

Dataset batch11_GSE235702
 - Cell types based on query "T cell": ['regulatory T cell', 'CD4-positive, alpha-beta memory T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell', 'gamma-delta T cell', 'naive thymus-derived CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 8589 cells, 32285 vars

Dataset batch11_GSE245820
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 1022 cells, 32285 vars

Dataset batch11_GSE247956
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 19751 cells, 32285 vars

Dataset batch11_GSE249200
 - Cell types based on query "T cell": []
Dataset batch11_GSE253294
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 2272 cells, 32285 vars

Dataset batch11_GSE254447_scRNAseq
 - Cell types based on query "T cell": []
Dataset batch11_GSE255405
 - Cell types based on query "T cell": []
Dataset batch12_GSE137665
 - Cell types based on query "T cell": []
Dataset batch12_GSE139107
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 358 cells, 32285 vars

Dataset batch12_GSE140023_10x
 - Cell types based on query "T cell": ['T cell', 'mature NK T cell', 'cytotoxic T cell']
 - n_obs, n_vars: 1452 cells, 32285 vars

Dataset batch12_GSE144471
 - Cell types based on query "T cell": []
Dataset batch12_GSE145095_mouse
 - Cell types based on query "T cell": ['T cell', 'regulatory T cell', 'naive thymus-derived CD8-positive, alpha-beta T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 4300 cells, 32285 vars

Dataset batch12_GSE149524
 - Cell types based on query "T cell": ['T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 50 cells, 32285 vars

Dataset batch12_GSE150338
 - Cell types based on query "T cell": []
Dataset batch12_GSE153192
 - Cell types based on query "T cell": ['regulatory T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell', 'gamma-delta T cell', 'naive thymus-derived CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta memory T cell']
 - n_obs, n_vars: 2301 cells, 32285 vars

Dataset batch12_GSE156497
 - Cell types based on query "T cell": []
Dataset batch12_GSE156905_mouse
 - Cell types based on query "T cell": ['naive thymus-derived CD8-positive, alpha-beta T cell', 'regulatory T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell', 'gamma-delta T cell']
 - n_obs, n_vars: 73 cells, 32285 vars

Dataset batch12_GSE157079
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 892 cells, 32285 vars

Dataset batch12_GSE166648
 - Cell types based on query "T cell": []
Dataset batch12_GSE193528
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 7621 cells, 32285 vars

Dataset batch12_GSE193584
 - Cell types based on query "T cell": []
Dataset batch12_GSE198621
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 3358 cells, 32285 vars

Dataset batch12_GSE202186
 - Cell types based on query "T cell": ['naive thymus-derived CD8-positive, alpha-beta T cell', 'gamma-delta T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell', 'regulatory T cell', 'CD4-positive, alpha-beta memory T cell']
 - n_obs, n_vars: 304031 cells, 32285 vars

Dataset batch12_GSE213925
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 18 cells, 32285 vars

Dataset batch12_GSE225503
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 2131 cells, 32285 vars

Dataset batch12_GSE227235
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 14 cells, 32285 vars

Dataset batch12_GSE233906_mouse
 - Cell types based on query "T cell": ['effector memory CD4-positive, alpha-beta T cell', 'regulatory T cell', 'mucosal-associated invariant T cell', 'alpha-beta T cell', 'CD8-positive, alpha-beta memory T cell, CD45RO-positive', 'naive thymus-derived CD4-positive, alpha-beta T cell', 'CD4-positive helper T cell', 'effector memory CD8-positive, alpha-beta T cell, terminally differentiated', 'gamma-delta T cell', 'naive thymus-derived CD8-positive, alpha-beta T cell', 'CD8-positive, alpha-beta memory T cell']
 - n_obs, n_vars: 10522 cells, 32285 vars

Dataset batch12_GSE239974
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 679 cells, 32285 vars

Dataset batch12_GSE239975
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 364 cells, 32285 vars

Dataset batch12_GSE245391
 - Cell types based on query "T cell": ['mature alpha-beta T cell']
 - n_obs, n_vars: 3 cells, 32285 vars

Dataset batch12_GSE251745
 - Cell types based on query "T cell": ['regulatory T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell', 'naive thymus-derived CD8-positive, alpha-beta T cell', 'gamma-delta T cell', 'CD4-positive, alpha-beta memory T cell']
 - n_obs, n_vars: 3435 cells, 32285 vars

Dataset batch12_GSE262306
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 32167 cells, 32285 vars

Dataset batch12_GSE267740
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 44222 cells, 32285 vars

Dataset batch13_CRA007803
 - Cell types based on query "T cell": []
Dataset batch13_CRA017680
 - Cell types based on query "T cell": ['mature NK T cell', 'CD8-positive, alpha-beta T cell', 'T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 8480 cells, 32285 vars

Dataset batch13_E-MTAB-8581_mouse
 - Cell types based on query "T cell": ['T cell', 'immature alpha-beta T cell', 'regulatory T cell', 'CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 1460 cells, 32285 vars

Dataset batch13_E-MTAB-9334
 - Cell types based on query "T cell": []
Dataset batch13_GSE121600_mouse
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 1 cells, 32285 vars

Dataset batch13_GSE121654
 - Cell types based on query "T cell": []
Dataset batch13_GSE155182
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 127 cells, 32285 vars

Dataset batch13_GSE163863
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 3 cells, 32285 vars

Dataset batch13_GSE183529
 - Cell types based on query "T cell": ['gamma-delta T cell', 'naive thymus-derived CD8-positive, alpha-beta T cell', 'regulatory T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell', 'CD4-positive, alpha-beta memory T cell']
 - n_obs, n_vars: 3230 cells, 32285 vars

Dataset batch13_GSE184707_mouse
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 19 cells, 32285 vars

Dataset batch13_GSE206175
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 11130 cells, 32285 vars

Dataset batch13_GSE206860
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 204 cells, 32285 vars

Dataset batch13_GSE218299
 - Cell types based on query "T cell": ['mature NK T cell', 'T cell', 'CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 1397 cells, 32285 vars

Dataset batch13_GSE221375
 - Cell types based on query "T cell": []
Dataset batch13_GSE223558
 - Cell types based on query "T cell": []
Dataset batch13_GSE224221
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 20 cells, 32285 vars

Dataset batch13_GSE228192
 - Cell types based on query "T cell": []
Dataset batch13_GSE233031
 - Cell types based on query "T cell": ['mature NK T cell', 'T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 463 cells, 32285 vars

Dataset batch13_GSE233511
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 41315 cells, 32285 vars

Dataset batch13_GSE236579
 - Cell types based on query "T cell": ['mature NK T cell', 'T cell']
 - n_obs, n_vars: 1757 cells, 32285 vars

Dataset batch13_GSE240419
 - Cell types based on query "T cell": ['naive thymus-derived CD8-positive, alpha-beta T cell', 'gamma-delta T cell', 'regulatory T cell', 'CD4-positive, alpha-beta memory T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 14447 cells, 32285 vars

Dataset batch13_GSE246768
 - Cell types based on query "T cell": []
Dataset batch13_GSE248172
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'T cell', 'mature NK T cell']
 - n_obs, n_vars: 697 cells, 32285 vars

Dataset batch13_GSE248173
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'T cell', 'mature NK T cell']
 - n_obs, n_vars: 749 cells, 32285 vars

Dataset batch13_GSE248174
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'T cell', 'mature NK T cell']
 - n_obs, n_vars: 1985 cells, 32285 vars

Dataset batch13_GSE252242
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 3977 cells, 32285 vars

Dataset batch13_GSE261088
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'mature NK T cell', 'CD4-positive, alpha-beta T cell', 'T cell']
 - n_obs, n_vars: 17656 cells, 32285 vars

Dataset batch13_GSE264408
 - Cell types based on query "T cell": ['regulatory T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell', 'gamma-delta T cell', 'CD4-positive, alpha-beta memory T cell', 'naive thymus-derived CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 12527 cells, 32285 vars

Dataset batch13_GSE264629
 - Cell types based on query "T cell": ['T cell', 'CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell', 'mature NK T cell', 'regulatory T cell']
 - n_obs, n_vars: 331 cells, 32285 vars

Dataset batch13_GSE267545
 - Cell types based on query "T cell": ['T cell', 'CD8-positive, alpha-beta T cell', 'mature NK T cell']
 - n_obs, n_vars: 905 cells, 32285 vars

Dataset batch13_GSE268494
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 424 cells, 32285 vars

Dataset batch13_GSE270875
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta cytotoxic T cell', 'CD4-positive, alpha-beta cytotoxic T cell', 'activated CD4-positive, alpha-beta T cell', 'activated CD8-positive, alpha-beta T cell', 'mature NK T cell']
 - n_obs, n_vars: 1746 cells, 32285 vars

Dataset batch13_GSE270904
 - Cell types based on query "T cell": ['activated CD4-positive, alpha-beta T cell', 'CD4-positive, alpha-beta cytotoxic T cell', 'CD8-positive, alpha-beta cytotoxic T cell', 'activated CD8-positive, alpha-beta T cell', 'mature NK T cell']
 - n_obs, n_vars: 19 cells, 32285 vars

Dataset batch13_GSE270961
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta cytotoxic T cell', 'CD4-positive, alpha-beta cytotoxic T cell', 'activated CD4-positive, alpha-beta T cell', 'activated CD8-positive, alpha-beta T cell', 'mature NK T cell']
 - n_obs, n_vars: 201 cells, 32285 vars

Dataset batch13_PRJNA1073234_mouse
 - Cell types based on query "T cell": []
Dataset batch13_PRJNA1117919
 - Cell types based on query "T cell": ['gamma-delta T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell', 'regulatory T cell', 'naive thymus-derived CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta memory T cell']
 - n_obs, n_vars: 49 cells, 32285 vars

Dataset batch13_PRJNA975496
 - Cell types based on query "T cell": ['T cell', 'naive thymus-derived CD8-positive, alpha-beta T cell', 'regulatory T cell']
 - n_obs, n_vars: 20 cells, 32285 vars

Dataset batch13_dat-61kfys3
 - Cell types based on query "T cell": []
Dataset batch13_np5hqbzzz
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 945 cells, 32285 vars

Dataset batch1_GSE136103_mouse
 - Cell types based on query "T cell": []
Dataset batch1_GSE152058_mouse
 - Cell types based on query "T cell": []
Dataset batch1_GSE158803_mouse
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 3865 cells, 32285 vars

Dataset batch3_E-MTAB-10196
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 1448 cells, 32285 vars

Dataset batch3_E-MTAB-10197
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 3 cells, 32285 vars

Dataset batch3_GSE137710_mouse
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 7 cells, 32285 vars

Dataset batch4_GSE201654_mouse
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 11 cells, 32285 vars

Dataset batch5_CRA007207
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 80716 cells, 32285 vars

Dataset batch5_GSE122465
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 331 cells, 32285 vars

Dataset batch5_GSE168737
 - Cell types based on query "T cell": []
Dataset batch5_GSE171993
 - Cell types based on query "T cell": []
Dataset batch5_GSE183288
 - Cell types based on query "T cell": ['T cell']

AnnData object with n_obs × n_vars = 1435782 × 32285
    obs: 'soma_joinid', 'orig.ident', 'nFeature_RNA', 'nCount_RNA', 'percent.mt', 'high_mt', 'high_ct', 'doublet_score', 'predicted_doublet', 'basic_qc', 'leiden', 'sample_id', 'author_cell_id', 'study_id', 'shortname', 'title', 'authors', 'pmid', 'doi', 'publication_date', 'study_description', 'repository', 'repository_identifier', 'repository_url', 'sample_number', 'Celltypist_Cell_Annotation', 'Celltypist_Cell_Annotation_Conf_Score', 'scArches_Cell_Annotation', 'scArches_Cell_Annotation_Uncert', 'author_cell_type', 'author_cell_type_cell_ontology_id', 'author_cell_type_cell_ontology_name', 'scArches_Cell_Type_Ontology_ID', 'scArches_Cell_Type_Ontology_Name', 'Celltypist_Cell_Type_Ontology_Name', 'Celltypist_Cell_Type_Ontology_ID', 'sample_type', 'sample_name', 'sample_cell_line_accession_cellosaurus', 'sample_cell_line_name_cellosaurus', 'sample_tissue', 'sample_tissue_uberon_id', 'sample_tissue_uberon_name', 'sample_pathology', 'sample_treatment', 'sample_treatment_mesh', 'sample_treatment_dose', 'sample_treatment_dose_unit', 'sample_treatment_exposure_duration', 'sample_collection_time', 'sample_collection_time_unit', 'sample_biomarkers', 'sample_replicate', 'sample_group', 'sample_library_preparation_EFO_id', 'sample_library_preparation_EFO_name', 'sample_instrument', 'sample_reference_genome', 'sample_other_information', 'cell_batch', 'cell_technology_type', 'experiment_platform', 'library_selection', 'rna_integrity_number', 'technology_type', 'sample_disease', 'sample_disease_id', 'sample_treatment_substance', 'sample_treatment_substance_id', 'sample_treatment_timepoint', 'sample_collection_method', 'sample_in_vivo_harvest_timepoint', 'sample_preservation_method', 'sample_treatment_timepoint_unit', 'donor_id', 'donor_organism', 'donor_strain', 'donor_race', 'donor_sex', 'donor_age', 'donor_age_unit', 'donor_disease', 'donor_disease_doid_id', 'donor_disease_doid_name', 'donor_disease_duration', 'donor_other_illness', 'donor_treatment', 'donor_treatment_mesh', 'donor_treatment_dose', 'donor_treatment_dose_unit', 'donor_treatment_route', 'donor_treatment_dose_frequency', 'donor_treatment_response', 'donor_tumor_stage', 'donor_tumor_diagnosis_time', 'donor_tumor_diagnosis_time_unit', 'donor_cancer_type', 'donor_smoking_history', 'donor_alcohol_use_history', 'donor_study_group', 'development_stage_ontology_name', 'development_stage_ontology_term_id', 'donor_disease_mondo_id', 'donor_disease_mondo_name', 'donor_genotype', 'organism_ontology_term_id', 'organism_ontology_term_name', 'sex_ontology_term_id', 'donor_treatment_mesh_id', 'batch', 'collection', 'scds', 'dataset_data_type', 'curation_dataset_id', 'dataset_repository', 'dataset_repository_url', 'dataset_workflow', 'source_experiment', 'experiment'

### Running the downstream pipeline with the query result

In [30]:
sc.pp.normalize_total(combined_adata, target_sum=1, exclude_highly_expressed=True, inplace=True)    # Normalization
print(combined_adata.X)

/home/anne.cooley/conda/envs/tiledbsoma/lib/python3.11/site-packages/legacy_api_wrap/__init__.py:88: UserWarning: Some cells have zero counts
  return fn(*args_all, **kw)

<Compressed Sparse Row sparse matrix of dtype 'float32'
	with 3150921988 stored elements and shape (1435782, 32285)>
  Coords	Values
  (0, 16)	0.03350786119699478
  (0, 20)	0.056754183024168015
  (0, 50)	0.03350786119699478
  (0, 52)	0.03350786119699478
  (0, 60)	0.0476527214050293
  (0, 63)	0.0476527214050293
  (0, 115)	0.03350786119699478
  (0, 118)	0.03350786119699478
  (0, 156)	0.0476527214050293
  (0, 178)	0.0476527214050293
  (0, 179)	0.0476527214050293
  (0, 193)	0.0476527214050293
  (0, 197)	0.03350786119699478
  (0, 198)	0.03350786119699478
  (0, 203)	0.03350786119699478
  (0, 206)	0.03350786119699478
  (0, 208)	0.03350786119699478
  (0, 210)	0.0476527214050293
  (0, 234)	0.0476527214050293
  (0, 238)	0.03350786119699478
  (0, 244)	0.03350786119699478
  (0, 326)	0.08030854165554047
  (0, 327)	0.03350786119699478
  (0, 334)	0.0476527214050293
  (0, 346)	0.06347811222076416
  :	:
  (1435781, 30027)	1.0
  (1435781, 30053)	1.2421947717666626
  (1435781, 30196)	1.3868573904037476
  (1435781, 30305)	1.0
  (1435781, 30337)	1.0
  (1435781, 30595)	1.0
  (1435781, 30612)	1.0
  (1435781, 30670)	1.0
  (1435781, 30854)	1.0
  (1435781, 30868)	1.0
  (1435781, 30869)	1.2421947717666626
  (1435781, 30932)	1.0
  (1435781, 31043)	1.0
  (1435781, 31062)	1.0
  (1435781, 31173)	1.2421947717666626
  (1435781, 31286)	1.0
  (1435781, 31287)	1.0
  (1435781, 31336)	1.0
  (1435781, 31344)	1.0
  (1435781, 31396)	1.0
  (1435781, 31479)	1.0
  (1435781, 32200)	1.0
  (1435781, 32201)	1.2421947717666626
  (1435781, 32205)	1.0
  (1435781, 32284)	1.0

**PCA plotting**

In [ ]:
sc.pp.pca(combined_adata)                                               # PCA computation
sc.pl.pca(combined_adata, color="scArches_Cell_Type_Ontology_Name")        # Scatter plot in PCA coordinates

**UMAP plotting**

In [ ]:
sc.pp.neighbors(combined_adata)
sc.tl.umap(combined_adata)
sc.pl.umap(combined_adata, color="scArches_Cell_Type_Ontology_Name")

In [33]:
combined_adata

AnnData object with n_obs × n_vars = 1435782 × 32285
    obs: 'soma_joinid', 'orig.ident', 'nFeature_RNA', 'nCount_RNA', 'percent.mt', 'high_mt', 'high_ct', 'doublet_score', 'predicted_doublet', 'basic_qc', 'leiden', 'sample_id', 'author_cell_id', 'study_id', 'shortname', 'title', 'authors', 'pmid', 'doi', 'publication_date', 'study_description', 'repository', 'repository_identifier', 'repository_url', 'sample_number', 'Celltypist_Cell_Annotation', 'Celltypist_Cell_Annotation_Conf_Score', 'scArches_Cell_Annotation', 'scArches_Cell_Annotation_Uncert', 'author_cell_type', 'author_cell_type_cell_ontology_id', 'author_cell_type_cell_ontology_name', 'scArches_Cell_Type_Ontology_ID', 'scArches_Cell_Type_Ontology_Name', 'Celltypist_Cell_Type_Ontology_Name', 'Celltypist_Cell_Type_Ontology_ID', 'sample_type', 'sample_name', 'sample_cell_line_accession_cellosaurus', 'sample_cell_line_name_cellosaurus', 'sample_tissue', 'sample_tissue_uberon_id', 'sample_tissue_uberon_name', 'sample_pathology', 'sample_treatment', 'sample_treatment_mesh', 'sample_treatment_dose', 'sample_treatment_dose_unit', 'sample_treatment_exposure_duration', 'sample_collection_time', 'sample_collection_time_unit', 'sample_biomarkers', 'sample_replicate', 'sample_group', 'sample_library_preparation_EFO_id', 'sample_library_preparation_EFO_name', 'sample_instrument', 'sample_reference_genome', 'sample_other_information', 'cell_batch', 'cell_technology_type', 'experiment_platform', 'library_selection', 'rna_integrity_number', 'technology_type', 'sample_disease', 'sample_disease_id', 'sample_treatment_substance', 'sample_treatment_substance_id', 'sample_treatment_timepoint', 'sample_collection_method', 'sample_in_vivo_harvest_timepoint', 'sample_preservation_method', 'sample_treatment_timepoint_unit', 'donor_id', 'donor_organism', 'donor_strain', 'donor_race', 'donor_sex', 'donor_age', 'donor_age_unit', 'donor_disease', 'donor_disease_doid_id', 'donor_disease_doid_name', 'donor_disease_duration', 'donor_other_illness', 'donor_treatment', 'donor_treatment_mesh', 'donor_treatment_dose', 'donor_treatment_dose_unit', 'donor_treatment_route', 'donor_treatment_dose_frequency', 'donor_treatment_response', 'donor_tumor_stage', 'donor_tumor_diagnosis_time', 'donor_tumor_diagnosis_time_unit', 'donor_cancer_type', 'donor_smoking_history', 'donor_alcohol_use_history', 'donor_study_group', 'development_stage_ontology_name', 'development_stage_ontology_term_id', 'donor_disease_mondo_id', 'donor_disease_mondo_name', 'donor_genotype', 'organism_ontology_term_id', 'organism_ontology_term_name', 'sex_ontology_term_id', 'donor_treatment_mesh_id', 'batch', 'collection', 'scds', 'dataset_data_type', 'curation_dataset_id', 'dataset_repository', 'dataset_repository_url', 'dataset_workflow', 'source_experiment', 'experiment'
    uns: 'pca', 'scArches_Cell_Type_Ontology_Name_colors', 'neighbors', 'umap'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'distances', 'connectivities'

In [ ]:
sc.pp.log1p(combined_adata)                                             # Logarithmic transformation
sc.pp.highly_variable_genes(combined_adata)                             # Annotate highly variable genes
sc.pp.filter_cells(combined_adata, min_genes=3)                         # Filter out cells with less than 3 genes expressed
combined_adata

**Querying for specific type of cells (e.g., "T cell") and nFeature_RNA > 500, in the experiments in Mouse_10x collection**

Run the below cell to define the function and then execute the code in the cell below it to query for a specific cell type across all experiments in the collection and combine results into a single Anndata object.

In [36]:
def query_based_on_cell_and_gene_in_collection(collection, cell_type_to_query, gene_parameter, min_features=0):
    collection_path = "s3://rancho-scrna-live/collections/" + collection
    collection = soma.Collection.open(collection_path)
    adatas = []

    for name, expt in collection.items():
        obs_df = expt.obs.read().concat().to_pandas()
        cell_type_labels = obs_df["scArches_Cell_Type_Ontology_Name"][(
            obs_df["scArches_Cell_Type_Ontology_Name"]
            .str.contains(cell_type_to_query, na=False)
        )].unique()

        print(f'Dataset {name} \n - Cell types based on query "{cell_type_to_query}": {list(cell_type_labels)}')

        if len(cell_type_labels) > 0:

            value_filter = (
                f"scArches_Cell_Type_Ontology_Name in {list(cell_type_labels)} "
                f"and {gene_parameter} > {min_features}"
            )

            with expt.axis_query(
                measurement_name="RNA",
                obs_query=soma.AxisQuery(
                    value_filter=value_filter
                )
            ) as query:
                print(f' - n_obs, n_vars: {query.n_obs} cells, {query.n_vars} vars\n')
                adata = query.to_anndata(X_name="data")
                adata.obs["source_experiment"] = name
                adatas.append(adata)

    combined_adata_2 = ad.concat(adatas, join="outer", label="experiment")
    return combined_adata_2

Run the below cell to query for a specific cell type across all experiments in the collection and combine results into a single Anndata object. You can update the collection and the cell type you want to query for as needed.

In [37]:
collection = 'Mouse_10x'
cell_type_to_query = 'T cell'
gene_parameter = 'nFeature_RNA'
min_features = 500
combined_adata2 = query_based_on_cell_and_gene_in_collection(collection, cell_type_to_query, gene_parameter, min_features)
combined_adata2

Dataset batch10_CRA010641
 - Cell types based on query "T cell": ['mature NK T cell', 'CD4-positive, alpha-beta T cell', 'T cell', 'CD8-positive, alpha-beta T cell', 'regulatory T cell', 'naive T cell']
 - n_obs, n_vars: 36308 cells, 32285 vars

Dataset batch10_GSE126836_mouse
 - Cell types based on query "T cell": []
Dataset batch10_GSE150742
 - Cell types based on query "T cell": ['T cell', 'mature NK T cell', 'CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell', 'regulatory T cell']
 - n_obs, n_vars: 1986 cells, 32285 vars

Dataset batch10_GSE164674
 - Cell types based on query "T cell": []
Dataset batch10_GSE175546
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'T cell', 'mature NK T cell']
 - n_obs, n_vars: 1480 cells, 32285 vars

Dataset batch10_GSE179501
 - Cell types based on query "T cell": ['mature NK T cell', 'CD4-positive, alpha-beta T cell', 'T cell', 'CD8-positive, alpha-beta T cell', 'regulatory T cell']
 - n_obs, n_vars: 5250 cells, 32285 vars

Dataset batch10_GSE179502
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 1 cells, 32285 vars

Dataset batch10_GSE198422
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 24228 cells, 32285 vars

Dataset batch10_GSE200366
 - Cell types based on query "T cell": []
Dataset batch10_GSE206835
 - Cell types based on query "T cell": ['mature alpha-beta T cell', 'CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 25043 cells, 32285 vars

Dataset batch10_GSE208152
 - Cell types based on query "T cell": []
Dataset batch10_GSE224688
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 1645 cells, 32285 vars

Dataset batch10_GSE230145
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 8 cells, 32285 vars

Dataset batch10_GSE235664
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta memory T cell', 'regulatory T cell', 'gamma-delta T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell', 'naive thymus-derived CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 24344 cells, 32285 vars

Dataset batch10_GSE235741
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta T cell', 'T cell', 'CD8-positive, alpha-beta T cell', 'regulatory T cell', 'naive T cell']
 - n_obs, n_vars: 1302 cells, 32285 vars

Dataset batch10_GSE244269
 - Cell types based on query "T cell": ['effector CD8-positive, alpha-beta T cell', 'T cell', 'mature NK T cell', 'effector CD4-positive, alpha-beta T cell', 'regulatory T cell']
 - n_obs, n_vars: 34025 cells, 32285 vars

Dataset batch10_GSE249412
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 120 cells, 32285 vars

Dataset batch10_GSE264530
 - Cell types based on query "T cell": ['naive thymus-derived CD8-positive, alpha-beta T cell', 'gamma-delta T cell', 'regulatory T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 9692 cells, 32285 vars

Dataset batch10_dat-717krsa_mouse
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'T cell', 'mature NK T cell']
 - n_obs, n_vars: 182 cells, 32285 vars

Dataset batch11_CNP0000892
 - Cell types based on query "T cell": []
Dataset batch11_GSE132910
 - Cell types based on query "T cell": []
Dataset batch11_GSE142637_mouse
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 5415 cells, 32285 vars

Dataset batch11_GSE143791_mouse
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 18099 cells, 32285 vars

Dataset batch11_GSE150178
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 3433 cells, 32285 vars

Dataset batch11_GSE154718
 - Cell types based on query "T cell": []
Dataset batch11_GSE161340
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'T cell']
 - n_obs, n_vars: 77 cells, 32285 vars

Dataset batch11_GSE169531
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 1 cells, 32285 vars

Dataset batch11_GSE181333
 - Cell types based on query "T cell": ['mature NK T cell', 'CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell', 'T cell']
 - n_obs, n_vars: 156 cells, 32285 vars

Dataset batch11_GSE189307
 - Cell types based on query "T cell": []
Dataset batch11_GSE191246
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 17704 cells, 32285 vars

Dataset batch11_GSE199880
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 1028 cells, 32285 vars

Dataset batch11_GSE205982
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 1 cells, 32285 vars

Dataset batch11_GSE209912
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'T cell']
 - n_obs, n_vars: 142 cells, 32285 vars

Dataset batch11_GSE210286
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 359 cells, 32285 vars

Dataset batch11_GSE210719
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 28488 cells, 32285 vars

Dataset batch11_GSE212837_mouse
 - Cell types based on query "T cell": []
Dataset batch11_GSE215070
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 3658 cells, 32285 vars

Dataset batch11_GSE216836
 - Cell types based on query "T cell": ['mature NK T cell', 'T cell', 'CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 9459 cells, 32285 vars

Dataset batch11_GSE216848
 - Cell types based on query "T cell": []
Dataset batch11_GSE220466
 - Cell types based on query "T cell": ['mature alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 1678 cells, 32285 vars

Dataset batch11_GSE223394
 - Cell types based on query "T cell": ['T cell', 'CD8-positive, alpha-beta T cell', 'mature NK T cell']
 - n_obs, n_vars: 16 cells, 32285 vars

Dataset batch11_GSE224398
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'mature NK T cell', 'T cell']
 - n_obs, n_vars: 137 cells, 32285 vars

Dataset batch11_GSE235702
 - Cell types based on query "T cell": ['regulatory T cell', 'CD4-positive, alpha-beta memory T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell', 'gamma-delta T cell', 'naive thymus-derived CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 8581 cells, 32285 vars

Dataset batch11_GSE245820
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 1013 cells, 32285 vars

Dataset batch11_GSE247956
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 19746 cells, 32285 vars

Dataset batch11_GSE249200
 - Cell types based on query "T cell": []
Dataset batch11_GSE253294
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 2267 cells, 32285 vars

Dataset batch11_GSE254447_scRNAseq
 - Cell types based on query "T cell": []
Dataset batch11_GSE255405
 - Cell types based on query "T cell": []
Dataset batch12_GSE137665
 - Cell types based on query "T cell": []
Dataset batch12_GSE139107
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 186 cells, 32285 vars

Dataset batch12_GSE140023_10x
 - Cell types based on query "T cell": ['T cell', 'mature NK T cell', 'cytotoxic T cell']
 - n_obs, n_vars: 1410 cells, 32285 vars

Dataset batch12_GSE144471
 - Cell types based on query "T cell": []
Dataset batch12_GSE145095_mouse
 - Cell types based on query "T cell": ['T cell', 'regulatory T cell', 'naive thymus-derived CD8-positive, alpha-beta T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 4273 cells, 32285 vars

Dataset batch12_GSE149524
 - Cell types based on query "T cell": ['T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 50 cells, 32285 vars

Dataset batch12_GSE150338
 - Cell types based on query "T cell": []
Dataset batch12_GSE153192
 - Cell types based on query "T cell": ['regulatory T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell', 'gamma-delta T cell', 'naive thymus-derived CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta memory T cell']
 - n_obs, n_vars: 1785 cells, 32285 vars

Dataset batch12_GSE156497
 - Cell types based on query "T cell": []
Dataset batch12_GSE156905_mouse
 - Cell types based on query "T cell": ['naive thymus-derived CD8-positive, alpha-beta T cell', 'regulatory T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell', 'gamma-delta T cell']
 - n_obs, n_vars: 70 cells, 32285 vars

Dataset batch12_GSE157079
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 879 cells, 32285 vars

Dataset batch12_GSE166648
 - Cell types based on query "T cell": []
Dataset batch12_GSE193528
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 7599 cells, 32285 vars

Dataset batch12_GSE193584
 - Cell types based on query "T cell": []
Dataset batch12_GSE198621
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 3348 cells, 32285 vars

Dataset batch12_GSE202186
 - Cell types based on query "T cell": ['naive thymus-derived CD8-positive, alpha-beta T cell', 'gamma-delta T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell', 'regulatory T cell', 'CD4-positive, alpha-beta memory T cell']
 - n_obs, n_vars: 302346 cells, 32285 vars

Dataset batch12_GSE213925
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 18 cells, 32285 vars

Dataset batch12_GSE225503
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 2087 cells, 32285 vars

Dataset batch12_GSE227235
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 13 cells, 32285 vars

Dataset batch12_GSE233906_mouse
 - Cell types based on query "T cell": ['effector memory CD4-positive, alpha-beta T cell', 'regulatory T cell', 'mucosal-associated invariant T cell', 'alpha-beta T cell', 'CD8-positive, alpha-beta memory T cell, CD45RO-positive', 'naive thymus-derived CD4-positive, alpha-beta T cell', 'CD4-positive helper T cell', 'effector memory CD8-positive, alpha-beta T cell, terminally differentiated', 'gamma-delta T cell', 'naive thymus-derived CD8-positive, alpha-beta T cell', 'CD8-positive, alpha-beta memory T cell']
 - n_obs, n_vars: 10146 cells, 32285 vars

Dataset batch12_GSE239974
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 678 cells, 32285 vars

Dataset batch12_GSE239975
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 362 cells, 32285 vars

Dataset batch12_GSE245391
 - Cell types based on query "T cell": ['mature alpha-beta T cell']
 - n_obs, n_vars: 3 cells, 32285 vars

Dataset batch12_GSE251745
 - Cell types based on query "T cell": ['regulatory T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell', 'naive thymus-derived CD8-positive, alpha-beta T cell', 'gamma-delta T cell', 'CD4-positive, alpha-beta memory T cell']
 - n_obs, n_vars: 3426 cells, 32285 vars

Dataset batch12_GSE262306
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 32053 cells, 32285 vars

Dataset batch12_GSE267740
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 44222 cells, 32285 vars

Dataset batch13_CRA007803
 - Cell types based on query "T cell": []
Dataset batch13_CRA017680
 - Cell types based on query "T cell": ['mature NK T cell', 'CD8-positive, alpha-beta T cell', 'T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 5719 cells, 32285 vars

Dataset batch13_E-MTAB-8581_mouse
 - Cell types based on query "T cell": ['T cell', 'immature alpha-beta T cell', 'regulatory T cell', 'CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 1448 cells, 32285 vars

Dataset batch13_E-MTAB-9334
 - Cell types based on query "T cell": []
Dataset batch13_GSE121600_mouse
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 1 cells, 32285 vars

Dataset batch13_GSE121654
 - Cell types based on query "T cell": []
Dataset batch13_GSE155182
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 125 cells, 32285 vars

Dataset batch13_GSE163863
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 3 cells, 32285 vars

Dataset batch13_GSE183529
 - Cell types based on query "T cell": ['gamma-delta T cell', 'naive thymus-derived CD8-positive, alpha-beta T cell', 'regulatory T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell', 'CD4-positive, alpha-beta memory T cell']
 - n_obs, n_vars: 3178 cells, 32285 vars

Dataset batch13_GSE184707_mouse
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 19 cells, 32285 vars

Dataset batch13_GSE206175
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 11011 cells, 32285 vars

Dataset batch13_GSE206860
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 129 cells, 32285 vars

Dataset batch13_GSE218299
 - Cell types based on query "T cell": ['mature NK T cell', 'T cell', 'CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 1067 cells, 32285 vars

Dataset batch13_GSE221375
 - Cell types based on query "T cell": []
Dataset batch13_GSE223558
 - Cell types based on query "T cell": []
Dataset batch13_GSE224221
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 19 cells, 32285 vars

Dataset batch13_GSE228192
 - Cell types based on query "T cell": []
Dataset batch13_GSE233031
 - Cell types based on query "T cell": ['mature NK T cell', 'T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 416 cells, 32285 vars

Dataset batch13_GSE233511
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 39625 cells, 32285 vars

Dataset batch13_GSE236579
 - Cell types based on query "T cell": ['mature NK T cell', 'T cell']
 - n_obs, n_vars: 1735 cells, 32285 vars

Dataset batch13_GSE240419
 - Cell types based on query "T cell": ['naive thymus-derived CD8-positive, alpha-beta T cell', 'gamma-delta T cell', 'regulatory T cell', 'CD4-positive, alpha-beta memory T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 14356 cells, 32285 vars

Dataset batch13_GSE246768
 - Cell types based on query "T cell": []
Dataset batch13_GSE248172
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'T cell', 'mature NK T cell']
 - n_obs, n_vars: 697 cells, 32285 vars

Dataset batch13_GSE248173
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'T cell', 'mature NK T cell']
 - n_obs, n_vars: 672 cells, 32285 vars

Dataset batch13_GSE248174
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'T cell', 'mature NK T cell']
 - n_obs, n_vars: 1793 cells, 32285 vars

Dataset batch13_GSE252242
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 3965 cells, 32285 vars

Dataset batch13_GSE261088
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'mature NK T cell', 'CD4-positive, alpha-beta T cell', 'T cell']
 - n_obs, n_vars: 16924 cells, 32285 vars

Dataset batch13_GSE264408
 - Cell types based on query "T cell": ['regulatory T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell', 'gamma-delta T cell', 'CD4-positive, alpha-beta memory T cell', 'naive thymus-derived CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 12414 cells, 32285 vars

Dataset batch13_GSE264629
 - Cell types based on query "T cell": ['T cell', 'CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell', 'mature NK T cell', 'regulatory T cell']
 - n_obs, n_vars: 331 cells, 32285 vars

Dataset batch13_GSE267545
 - Cell types based on query "T cell": ['T cell', 'CD8-positive, alpha-beta T cell', 'mature NK T cell']
 - n_obs, n_vars: 905 cells, 32285 vars

Dataset batch13_GSE268494
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 423 cells, 32285 vars

Dataset batch13_GSE270875
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta cytotoxic T cell', 'CD4-positive, alpha-beta cytotoxic T cell', 'activated CD4-positive, alpha-beta T cell', 'activated CD8-positive, alpha-beta T cell', 'mature NK T cell']
 - n_obs, n_vars: 1735 cells, 32285 vars

Dataset batch13_GSE270904
 - Cell types based on query "T cell": ['activated CD4-positive, alpha-beta T cell', 'CD4-positive, alpha-beta cytotoxic T cell', 'CD8-positive, alpha-beta cytotoxic T cell', 'activated CD8-positive, alpha-beta T cell', 'mature NK T cell']
 - n_obs, n_vars: 19 cells, 32285 vars

Dataset batch13_GSE270961
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta cytotoxic T cell', 'CD4-positive, alpha-beta cytotoxic T cell', 'activated CD4-positive, alpha-beta T cell', 'activated CD8-positive, alpha-beta T cell', 'mature NK T cell']
 - n_obs, n_vars: 199 cells, 32285 vars

Dataset batch13_PRJNA1073234_mouse
 - Cell types based on query "T cell": []
Dataset batch13_PRJNA1117919
 - Cell types based on query "T cell": ['gamma-delta T cell', 'naive thymus-derived CD4-positive, alpha-beta T cell', 'regulatory T cell', 'naive thymus-derived CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta memory T cell']
 - n_obs, n_vars: 49 cells, 32285 vars

Dataset batch13_PRJNA975496
 - Cell types based on query "T cell": ['T cell', 'naive thymus-derived CD8-positive, alpha-beta T cell', 'regulatory T cell']
 - n_obs, n_vars: 20 cells, 32285 vars

Dataset batch13_dat-61kfys3
 - Cell types based on query "T cell": []
Dataset batch13_np5hqbzzz
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 937 cells, 32285 vars

Dataset batch1_GSE136103_mouse
 - Cell types based on query "T cell": []
Dataset batch1_GSE152058_mouse
 - Cell types based on query "T cell": []
Dataset batch1_GSE158803_mouse
 - Cell types based on query "T cell": ['CD8-positive, alpha-beta T cell', 'CD4-positive, alpha-beta T cell']
 - n_obs, n_vars: 2947 cells, 32285 vars

Dataset batch3_E-MTAB-10196
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 1448 cells, 32285 vars

Dataset batch3_E-MTAB-10197
 - Cell types based on query "T cell": ['CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell']
 - n_obs, n_vars: 3 cells, 32285 vars

Dataset batch3_GSE137710_mouse
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 7 cells, 32285 vars

Dataset batch4_GSE201654_mouse
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 11 cells, 32285 vars

Dataset batch5_CRA007207
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 80582 cells, 32285 vars

Dataset batch5_GSE122465
 - Cell types based on query "T cell": ['T cell']
 - n_obs, n_vars: 327 cells, 32285 vars

Dataset batch5_GSE168737
 - Cell types based on query "T cell": []
Dataset batch5_GSE171993
 - Cell types based on query "T cell": []
Dataset batch5_GSE183288
 - Cell types based on query "T cell": ['T cell']

AnnData object with n_obs × n_vars = 1403117 × 32285
    obs: 'soma_joinid', 'orig.ident', 'nFeature_RNA', 'nCount_RNA', 'percent.mt', 'high_mt', 'high_ct', 'doublet_score', 'predicted_doublet', 'basic_qc', 'leiden', 'sample_id', 'author_cell_id', 'study_id', 'shortname', 'title', 'authors', 'pmid', 'doi', 'publication_date', 'study_description', 'repository', 'repository_identifier', 'repository_url', 'sample_number', 'Celltypist_Cell_Annotation', 'Celltypist_Cell_Annotation_Conf_Score', 'scArches_Cell_Annotation', 'scArches_Cell_Annotation_Uncert', 'author_cell_type', 'author_cell_type_cell_ontology_id', 'author_cell_type_cell_ontology_name', 'scArches_Cell_Type_Ontology_ID', 'scArches_Cell_Type_Ontology_Name', 'Celltypist_Cell_Type_Ontology_Name', 'Celltypist_Cell_Type_Ontology_ID', 'sample_type', 'sample_name', 'sample_cell_line_accession_cellosaurus', 'sample_cell_line_name_cellosaurus', 'sample_tissue', 'sample_tissue_uberon_id', 'sample_tissue_uberon_name', 'sample_pathology', 'sample_treatment', 'sample_treatment_mesh', 'sample_treatment_dose', 'sample_treatment_dose_unit', 'sample_treatment_exposure_duration', 'sample_collection_time', 'sample_collection_time_unit', 'sample_biomarkers', 'sample_replicate', 'sample_group', 'sample_library_preparation_EFO_id', 'sample_library_preparation_EFO_name', 'sample_instrument', 'sample_reference_genome', 'sample_other_information', 'cell_batch', 'cell_technology_type', 'experiment_platform', 'library_selection', 'rna_integrity_number', 'technology_type', 'sample_disease', 'sample_disease_id', 'sample_treatment_substance', 'sample_treatment_substance_id', 'sample_treatment_timepoint', 'sample_collection_method', 'sample_in_vivo_harvest_timepoint', 'sample_preservation_method', 'sample_treatment_timepoint_unit', 'donor_id', 'donor_organism', 'donor_strain', 'donor_race', 'donor_sex', 'donor_age', 'donor_age_unit', 'donor_disease', 'donor_disease_doid_id', 'donor_disease_doid_name', 'donor_disease_duration', 'donor_other_illness', 'donor_treatment', 'donor_treatment_mesh', 'donor_treatment_dose', 'donor_treatment_dose_unit', 'donor_treatment_route', 'donor_treatment_dose_frequency', 'donor_treatment_response', 'donor_tumor_stage', 'donor_tumor_diagnosis_time', 'donor_tumor_diagnosis_time_unit', 'donor_cancer_type', 'donor_smoking_history', 'donor_alcohol_use_history', 'donor_study_group', 'development_stage_ontology_name', 'development_stage_ontology_term_id', 'donor_disease_mondo_id', 'donor_disease_mondo_name', 'donor_genotype', 'organism_ontology_term_id', 'organism_ontology_term_name', 'sex_ontology_term_id', 'donor_treatment_mesh_id', 'batch', 'collection', 'scds', 'dataset_data_type', 'curation_dataset_id', 'dataset_repository', 'dataset_repository_url', 'dataset_workflow', 'source_experiment', 'experiment'

### Find experiments that express a particular gene

The cell-type searches above filter `obs` (cell annotations). A gene's expression is not in `obs` — it lives in the `X` matrix, indexed by `var` (the gene table). To search by gene you select it with a **`var_query`** instead of an `obs_query`, then read the counts.

The function below loops over every experiment in a collection and, for each one:

1. selects the gene on the `var` axis (`var_id` is the gene symbol; use `gene_ids` for Ensembl IDs);
2. reports whether the gene is measured at all (`n_vars == 0` means it isn't in that experiment's `var`);
3. reads the `counts` layer for that single gene and counts how many cells express it above `min_count`.

It returns a summary DataFrame across the collection.

In [35]:
def find_experiments_expressing_gene(collection, gene, min_count=0, gene_column="var_id"):
    """Report, per experiment in a collection, how many cells express `gene`."""
    collection_path = "s3://rancho-scrna-live/collections/" + collection
    rows = []

    with soma.Collection.open(collection_path) as coll:
        for name, expt in coll.items():
            with expt.axis_query(
                measurement_name="RNA",
                var_query=soma.AxisQuery(value_filter=f"{gene_column} == '{gene}'"),
            ) as query:
                if query.n_vars == 0:
                    print(f"{name}: gene '{gene}' not measured")
                    rows.append({"experiment": name, "measured": False,
                                 "n_expressing": 0, "n_cells": query.n_obs, "pct": 0.0})
                    continue

                # Long-form table of nonzero entries for this one gene: soma_data = count
                x = query.X("counts").tables().concat().to_pandas()
                n_expressing = int((x["soma_data"] > min_count).sum())
                pct = 100 * n_expressing / query.n_obs if query.n_obs else 0.0
                print(f"{name}: {n_expressing:,}/{query.n_obs:,} cells "
                      f"express {gene} (> {min_count})  [{pct:.1f}%]")
                rows.append({"experiment": name, "measured": True,
                             "n_expressing": n_expressing, "n_cells": query.n_obs,
                             "pct": round(pct, 1)})

    return pd.DataFrame(rows).sort_values("n_expressing", ascending=False).reset_index(drop=True)

Run it across a collection — e.g. `CD8A` in `Human_ss2`:

In [38]:
gene_summary = find_experiments_expressing_gene("Human_10x", gene="KISS1", min_count=0)
gene_summary

batch10_E-MTAB-12339: 5,039/133,603 cells express KISS1 (> 0)  [3.8%]
batch10_E-MTAB-13664: 9,611/993,866 cells express KISS1 (> 0)  [1.0%]
batch10_GSE112271: 286/43,124 cells express KISS1 (> 0)  [0.7%]
batch10_GSE126836_human: 6/80,307 cells express KISS1 (> 0)  [0.0%]
batch10_GSE136035: 2/24,643 cells express KISS1 (> 0)  [0.0%]
batch10_GSE137829: 1,279/49,013 cells express KISS1 (> 0)  [2.6%]
batch10_GSE141578: 0/23,728 cells express KISS1 (> 0)  [0.0%]
batch10_GSE143706: 1,303/37,276 cells express KISS1 (> 0)  [3.5%]
batch10_GSE148434: 6/37,528 cells express KISS1 (> 0)  [0.0%]
batch10_GSE150290: 1,839/219,463 cells express KISS1 (> 0)  [0.8%]
batch10_GSE153765: 0/8,975 cells express KISS1 (> 0)  [0.0%]
batch10_GSE161192: 0/6,178 cells express KISS1 (> 0)  [0.0%]
batch10_GSE163558: 127/45,396 cells express KISS1 (> 0)  [0.3%]
batch10_GSE164690: 156/138,069 cells express KISS1 (> 0)  [0.1%]
batch10_GSE168668: 254/12,176 cells express KISS1 (> 0)  [2.1%]
batch10_GSE168933: 12/44,896 cells express KISS1 (> 0)  [0.0%]
batch10_GSE170673: 6/20,784 cells express KISS1 (> 0)  [0.0%]
batch10_GSE173468: 87/75,142 cells express KISS1 (> 0)  [0.1%]
batch10_GSE176160: 103/38,853 cells express KISS1 (> 0)  [0.3%]
batch10_GSE180122: 230/151,336 cells express KISS1 (> 0)  [0.2%]
batch10_GSE186538_human: 511/259,606 cells express KISS1 (> 0)  [0.2%]
batch10_GSE188737: 69/40,271 cells express KISS1 (> 0)  [0.2%]
batch10_GSE189040: 0/59,733 cells express KISS1 (> 0)  [0.0%]
batch10_GSE189754: 1/81,201 cells express KISS1 (> 0)  [0.0%]
batch10_GSE190564: 56/54,100 cells express KISS1 (> 0)  [0.1%]
batch10_GSE193337: 45/27,303 cells express KISS1 (> 0)  [0.2%]
batch10_GSE193688: 25/65,385 cells express KISS1 (> 0)  [0.0%]
batch10_GSE194245: 0/10,866 cells express KISS1 (> 0)  [0.0%]
batch10_GSE196936: 80/1,864 cells express KISS1 (> 0)  [4.3%]
batch10_GSE197677: 135/182,208 cells express KISS1 (> 0)  [0.1%]
batch10_GSE202601: 3/37,189 cells express KISS1 (> 0)  [0.0%]
batch10_GSE205049: 13/33,154 cells express KISS1 (> 0)  [0.0%]
batch10_GSE205589: 13/32,736 cells express KISS1 (> 0)  [0.0%]
batch10_GSE210038: 73/87,677 cells express KISS1 (> 0)  [0.1%]
batch10_GSE210679: 415/17,151 cells express KISS1 (> 0)  [2.4%]
batch10_GSE212109: 332/40,929 cells express KISS1 (> 0)  [0.8%]
batch10_GSE213569: 14/4,866 cells express KISS1 (> 0)  [0.3%]
batch10_GSE213740: 138/96,542 cells express KISS1 (> 0)  [0.1%]
batch10_GSE220116: 250/50,226 cells express KISS1 (> 0)  [0.5%]
batch10_GSE223178: 2/16,343 cells express KISS1 (> 0)  [0.0%]
batch10_GSE225170: 1/6,736 cells express KISS1 (> 0)  [0.0%]
batch10_GSE226077: 4/76,626 cells express KISS1 (> 0)  [0.0%]
batch10_GSE226427: 1/36,432 cells express KISS1 (> 0)  [0.0%]
batch10_GSE227136: 1,622/724,219 cells express KISS1 (> 0)  [0.2%]
batch10_GSE228165: 9/280,241 cells express KISS1 (> 0)  [0.0%]
batch10_GSE231540: 660/206,626 cells express KISS1 (> 0)  [0.3%]
batch10_GSE235663: 1/16,397 cells express KISS1 (> 0)  [0.0%]
batch10_GSE237254: 4/33,771 cells express KISS1 (> 0)  [0.0%]
batch10_GSE242086: 127/50,331 cells express KISS1 (> 0)  [0.3%]
batch10_GSE243076: 183/57,915 cells express KISS1 (> 0)  [0.3%]
batch10_GSE243639: 118/141,145 cells express KISS1 (> 0)  [0.1%]
batch10_GSE244267: 364/81,855 cells express KISS1 (> 0)  [0.4%]
batch10_PRJNA679848: 364/70,543 cells express KISS1 (> 0)  [0.5%]
batch10_PRJNA726991: 9/15,455 cells express KISS1 (> 0)  [0.1%]
batch10_PRJNA916657: 325/986,368 cells express KISS1 (> 0)  [0.0%]
batch10_SRP403458: 4/70,405 cells express KISS1 (> 0)  [0.0%]
batch10_dat-717krsa_human: 79/50,257 cells express KISS1 (> 0)  [0.2%]
batch11_GSE130157: 3/71,228 cells express KISS1 (> 0)  [0.0%]
batch11_GSE132914: 205/11,415 cells express KISS1 (> 0)  [1.8%]
batch11_GSE138693: 457/6,248 cells express KISS1 (> 0)  [7.3%]
batch11_GSE142637_human: 0/21,049 cells express KISS1 (> 0)  [0.0%]
batch11_GSE143791_human: 14/138,041 cells express KISS1 (> 0)  [0.0%]
batch11_GSE146981: 2,003/66,353 cells express KISS1 (> 0)  [3.0%]
batch11_GSE164564: 9/32,520 cells express KISS1 (> 0)  [0.0%]
batch11_GSE178245: 6/34,797 cells express KISS1 (> 0)  [0.0%]
batch11_GSE182527: 0/10,701 cells express KISS1 (> 0)  [0.0%]
batch11_GSE185834: 82/114,730 cells express KISS1 (> 0)  [0.1%]
batch11_GSE185991: 48/119,119 cells express KISS1 (> 0)  [0.0%]
batch11_GSE189519: 529/17,033 cells express KISS1 (> 0)  [3.1%]
batch11_GSE190559: 125/18,194 cells express KISS1 (> 0)  [0.7%]
batch11_GSE193304: 64/160,554 cells express KISS1 (> 0)  [0.0%]
batch11_GSE199994: 7/71,733 cells express KISS1 (> 0)  [0.0%]
batch11_GSE207935: 2/139,522 cells express KISS1 (> 0)  [0.0%]
batch11_GSE210963: 2/24,040 cells express KISS1 (> 0)  [0.0%]
batch11_GSE212837_human: 478/173,961 cells express KISS1 (> 0)  [0.3%]
batch11_GSE212966: 290/54,898 cells express KISS1 (> 0)  [0.5%]
batch11_GSE213902: 1/7,231 cells express KISS1 (> 0)  [0.0%]
batch11_GSE218985: 2/116,790 cells express KISS1 (> 0)  [0.0%]
batch11_GSE222649: 738/58,598 cells express KISS1 (> 0)  [1.3%]
batch11_GSE226225: 10,592/46,087 cells express KISS1 (> 0)  [23.0%]
batch11_GSE231993: 19/41,779 cells express KISS1 (> 0)  [0.0%]
batch11_GSE233280: 33/43,597 cells express KISS1 (> 0)  [0.1%]
batch11_GSE233405: 0/25,277 cells express KISS1 (> 0)  [0.0%]
batch11_GSE233844: 12/151,997 cells express KISS1 (> 0)  [0.0%]
batch11_GSE233917: 6/30,474 cells express KISS1 (> 0)  [0.0%]
batch11_GSE234790: 100/31,783 cells express KISS1 (> 0)  [0.3%]
batch11_GSE235168: 385/38,008 cells express KISS1 (> 0)  [1.0%]
batch11_GSE244781: 624/120,253 cells express KISS1 (> 0)  [0.5%]
batch11_GSE249279: 97/120,958 cells express KISS1 (> 0)  [0.1%]
batch11_HRA000704: 427/152,358 cells express KISS1 (> 0)  [0.3%]
batch12_E-MTAB-11188: 3/237,992 cells express KISS1 (> 0)  [0.0%]
batch12_E-MTAB-11792: 4/12,268 cells express KISS1 (> 0)  [0.0%]
batch12_GSE119212: 8/52,042 cells express KISS1 (> 0)  [0.0%]
batch12_GSE130105: 2/21,414 cells express KISS1 (> 0)  [0.0%]
batch12_GSE145095_human: 0/1,615 cells express KISS1 (> 0)  [0.0%]
batch12_GSE145154: 60/173,578 cells express KISS1 (> 0)  [0.0%]
batch12_GSE150672_10x: 2/10,632 cells express KISS1 (> 0)  [0.0%]
batch12_GSE155488: 12/49,639 cells express KISS1 (> 0)  [0.0%]
batch12_GSE156905_human: 7/17,080 cells express KISS1 (> 0)  [0.0%]
batch12_GSE161470: 2/16,103 cells express KISS1 (> 0)  [0.0%]
batch12_GSE163005: 2/87,913 cells express KISS1 (> 0)  [0.0%]
batch12_GSE163973: 82/41,100 cells express KISS1 (> 0)  [0.2%]
batch12_GSE174232: 3/9,664 cells express KISS1 (> 0)  [0.0%]
batch12_GSE176029: 5/7,819 cells express KISS1 (> 0)  [0.1%]
batch12_GSE178317: 595/49,041 cells express KISS1 (> 0)  [1.2%]
batch12_GSE178481: 33/198,709 cells express KISS1 (> 0)  [0.0%]
batch12_GSE180928: 303/113,201 cells express KISS1 (> 0)  [0.3%]
batch12_GSE186476: 37/56,872 cells express KISS1 (> 0)  [0.1%]
batch12_GSE187877: 0/4,494 cells express KISS1 (> 0)  [0.0%]
batch12_GSE191301: 33/31,877 cells express KISS1 (> 0)  [0.1%]
batch12_GSE193102: 143/53,836 cells express KISS1 (> 0)  [0.3%]
batch12_GSE193181: 5/252,710 cells express KISS1 (> 0)  [0.0%]
batch12_GSE195832: 49/49,733 cells express KISS1 (> 0)  [0.1%]
batch12_GSE199013: 290/195,100 cells express KISS1 (> 0)  [0.1%]
batch12_GSE199711: 11/12,864 cells express KISS1 (> 0)  [0.1%]
batch12_GSE200253: 2/12,949 cells express KISS1 (> 0)  [0.0%]
batch12_GSE201348: 134/276,610 cells express KISS1 (> 0)  [0.0%]
batch12_GSE202379: 997/91,708 cells express KISS1 (> 0)  [1.1%]
batch12_GSE205554: 4/6,604 cells express KISS1 (> 0)  [0.1%]
batch12_GSE212447: 18/60,196 cells express KISS1 (> 0)  [0.0%]
batch12_GSE213015: 10/4,210 cells express KISS1 (> 0)  [0.2%]
batch12_GSE224527: 0/1,876 cells express KISS1 (> 0)  [0.0%]
batch12_GSE226329: 554/13,630 cells express KISS1 (> 0)  [4.1%]
batch12_GSE227835: 15/369,744 cells express KISS1 (> 0)  [0.0%]
batch12_GSE228499: 756/23,501 cells express KISS1 (> 0)  [3.2%]
batch12_GSE233906_human: 11/36,561 cells express KISS1 (> 0)  [0.0%]
batch12_GSE236566: 117/183,711 cells express KISS1 (> 0)  [0.1%]
batch12_GSE236738: 172/41,076 cells express KISS1 (> 0)  [0.4%]
batch12_GSE241453: 481/92,638 cells express KISS1 (> 0)  [0.5%]
batch12_GSE248907: 756/54,199 cells express KISS1 (> 0)  [1.4%]
batch12_GSE256490: 3,673/478,024 cells express KISS1 (> 0)  [0.8%]
batch12_GSE256491: 368/80,868 cells express KISS1 (> 0)  [0.5%]
batch12_GSE256493: 4,041/558,892 cells express KISS1 (> 0)  [0.7%]
batch12_GSE263156: 0/14,590 cells express KISS1 (> 0)  [0.0%]
batch12_GSE263747: 3,592/37,353 cells express KISS1 (> 0)  [9.6%]
batch12_GSE263995: 36/89,724 cells express KISS1 (> 0)  [0.0%]
batch12_GSE264573: 170/6,329 cells express KISS1 (> 0)  [2.7%]
batch12_GSE266219: 64/611,163 cells express KISS1 (> 0)  [0.0%]
batch12_HRA002370: 14/119,377 cells express KISS1 (> 0)  [0.0%]
batch13_E-MTAB-10060_fibroblast: 10/58,278 cells express KISS1 (> 0)  [0.0%]
batch13_E-MTAB-10060_iPSC: 57/17,469 cells express KISS1 (> 0)  [0.3%]
batch13_E-MTAB-11036: 2/75,329 cells express KISS1 (> 0)  [0.0%]
batch13_E-MTAB-11149: 9/11,172 cells express KISS1 (> 0)  [0.1%]
batch13_E-MTAB-11953: 2,572/17,985 cells express KISS1 (> 0)  [14.3%]
batch13_E-MTAB-14050: 9/29,277 cells express KISS1 (> 0)  [0.0%]
batch13_E-MTAB-7189: 403/6,678 cells express KISS1 (> 0)  [6.0%]
batch13_E-MTAB-8210: 10,993/107,439 cells express KISS1 (> 0)  [10.2%]
batch13_E-MTAB-8581_human: 525/339,556 cells express KISS1 (> 0)  [0.2%]
batch13_GSE114239: 46/35,687 cells express KISS1 (> 0)  [0.1%]
batch13_GSE114373: 196/72,209 cells express KISS1 (> 0)  [0.3%]
batch13_GSE121600_human: 1,687/53,133 cells express KISS1 (> 0)  [3.2%]
batch13_GSE124992: 26/21,359 cells express KISS1 (> 0)  [0.1%]
batch13_GSE125422: 45/37,360 cells express KISS1 (> 0)  [0.1%]
batch13_GSE129933: 0/588 cells express KISS1 (> 0)  [0.0%]
batch13_GSE130731: 124/31,827 cells express KISS1 (> 0)  [0.4%]
batch13_GSE131094: 104/74,372 cells express KISS1 (> 0)  [0.1%]
batch13_GSE134174: 3,897/36,729 cells express KISS1 (> 0)  [10.6%]
batch13_GSE134649: 0/9,354 cells express KISS1 (> 0)  [0.0%]
batch13_GSE135253: 72/3,853 cells express KISS1 (> 0)  [1.9%]
batch13_GSE136929: 9/20,856 cells express KISS1 (> 0)  [0.0%]
batch13_GSE137672: 2/7,347 cells express KISS1 (> 0)  [0.0%]
batch13_GSE138979: 653/38,479 cells express KISS1 (> 0)  [1.7%]
batch13_GSE140405: 63/4,635 cells express KISS1 (> 0)  [1.4%]
batch13_GSE141319: 634/7,214 cells express KISS1 (> 0)  [8.8%]
batch13_GSE144024: 572/52,799 cells express KISS1 (> 0)  [1.1%]
batch13_GSE144477: 38/10,834 cells express KISS1 (> 0)  [0.4%]
batch13_GSE144897: 3/3,041 cells express KISS1 (> 0)  [0.1%]
batch13_GSE145328: 2/26,479 cells express KISS1 (> 0)  [0.0%]
batch13_GSE145926: 100/74,115 cells express KISS1 (> 0)  [0.1%]
batch13_GSE146341: 61/11,698 cells express KISS1 (> 0)  [0.5%]
batch13_GSE147047: 119/24,677 cells express KISS1 (> 0)  [0.5%]
batch13_GSE147694: 144/14,566 cells express KISS1 (> 0)  [1.0%]
batch13_GSE148212: 6/1,358 cells express KISS1 (> 0)  [0.4%]
batch13_GSE148673: 311/46,135 cells express KISS1 (> 0)  [0.7%]
batch13_GSE149136: 2/12,884 cells express KISS1 (> 0)  [0.0%]
batch13_GSE150570: 29/6,713 cells express KISS1 (> 0)  [0.4%]
batch13_GSE150741: 140/14,308 cells express KISS1 (> 0)  [1.0%]
batch13_GSE151671: 22/6,397 cells express KISS1 (> 0)  [0.3%]
batch13_GSE151918: 1/6,820 cells express KISS1 (> 0)  [0.0%]
batch13_GSE152938: 27/30,578 cells express KISS1 (> 0)  [0.1%]
batch13_GSE155226: 176/13,635 cells express KISS1 (> 0)  [1.3%]
batch13_GSE155795: 1/7,090 cells express KISS1 (> 0)  [0.0%]
batch13_GSE156753: 794/17,515 cells express KISS1 (> 0)  [4.5%]
batch13_GSE157157: 202/26,850 cells express KISS1 (> 0)  [0.8%]
batch13_GSE157525: 51/37,687 cells express KISS1 (> 0)  [0.1%]
batch13_GSE158955: 13/36,731 cells express KISS1 (> 0)  [0.0%]
batch13_GSE159117_GSE159113: 0/18,311 cells express KISS1 (> 0)  [0.0%]
batch13_GSE159354: 1,547/172,041 cells express KISS1 (> 0)  [0.9%]
batch13_GSE159585: 479/210,618 cells express KISS1 (> 0)  [0.2%]
batch13_GSE159805: 4/1,151 cells express KISS1 (> 0)  [0.3%]
batch13_GSE160810: 13/80,919 cells express KISS1 (> 0)  [0.0%]
batch13_GSE162122: 70/163,087 cells express KISS1 (> 0)  [0.0%]
batch13_GSE162454: 12/39,638 cells express KISS1 (> 0)  [0.0%]
batch13_GSE162547: 1,117/14,749 cells express KISS1 (> 0)  [7.6%]
batch13_GSE163423: 64/18,348 cells express KISS1 (> 0)  [0.3%]
batch13_GSE163445: 562/16,484 cells express KISS1 (> 0)  [3.4%]
batch13_GSE163505: 67/16,394 cells express KISS1 (> 0)  [0.4%]
batch13_GSE164089: 107/27,056 cells express KISS1 (> 0)  [0.4%]
batch13_GSE164891: 567/6,576 cells express KISS1 (> 0)  [8.6%]
batch13_GSE166635: 89/21,128 cells express KISS1 (> 0)  [0.4%]
batch13_GSE169074: 36/12,356 cells express KISS1 (> 0)  [0.3%]
batch13_GSE169751: 20/27,814 cells express KISS1 (> 0)  [0.1%]
batch13_GSE171344: 2,725/225,121 cells express KISS1 (> 0)  [1.2%]
batch13_GSE171768: 177/5,653 cells express KISS1 (> 0)  [3.1%]
batch13_GSE174200: 3,963/176,473 cells express KISS1 (> 0)  [2.2%]
batch13_GSE174748: 241/15,087 cells express KISS1 (> 0)  [1.6%]
batch13_GSE175719: 522/64,261 cells express KISS1 (> 0)  [0.8%]
batch13_GSE178325: 2,529/145,072 cells express KISS1 (> 0)  [1.7%]
batch13_GSE178379: 2/4,045 cells express KISS1 (> 0)  [0.0%]
batch13_GSE181061: 9/108,867 cells express KISS1 (> 0)  [0.0%]
batch13_GSE181297: 23/22,694 cells express KISS1 (> 0)  [0.1%]
batch13_GSE181595: 10/24,936 cells express KISS1 (> 0)  [0.0%]
batch13_GSE184707_human: 3/23,182 cells express KISS1 (> 0)  [0.0%]
batch13_GSE185026: 222/24,605 cells express KISS1 (> 0)  [0.9%]
batch13_GSE185477: 381/54,647 cells express KISS1 (> 0)  [0.7%]
batch13_GSE186301: 24/24,506 cells express KISS1 (> 0)  [0.1%]
batch13_GSE188823: 527/16,594 cells express KISS1 (> 0)  [3.2%]
batch13_GSE189460: 21/107,292 cells express KISS1 (> 0)  [0.0%]
batch13_GSE193485: 0/8,706 cells express KISS1 (> 0)  [0.0%]
batch13_GSE195667: 0/21,070 cells express KISS1 (> 0)  [0.0%]
batch13_GSE195911: 644/10,430 cells express KISS1 (> 0)  [6.2%]
batch13_GSE196280: 4/9,121 cells express KISS1 (> 0)  [0.0%]
batch13_GSE196365: 20/5,187 cells express KISS1 (> 0)  [0.4%]
batch13_GSE202109: 9/6,492 cells express KISS1 (> 0)  [0.1%]
batch13_GSE202210: 537/66,918 cells express KISS1 (> 0)  [0.8%]
batch13_GSE203530: 1,408/49,675 cells express KISS1 (> 0)  [2.8%]
batch13_GSE205977: 1/25,867 cells express KISS1 (> 0)  [0.0%]
batch13_GSE209832: 1/26,501 cells express KISS1 (> 0)  [0.0%]
batch13_GSE210199: 58/20,797 cells express KISS1 (> 0)  [0.3%]
batch13_GSE213288: 6/2,431 cells express KISS1 (> 0)  [0.2%]
batch13_GSE213330: 59/107,294 cells express KISS1 (> 0)  [0.1%]
batch13_GSE214085: 278/57,025 cells express KISS1 (> 0)  [0.5%]
batch13_GSE214088: 21/21,169 cells express KISS1 (> 0)  [0.1%]
batch13_GSE214283: 113/454,176 cells express KISS1 (> 0)  [0.0%]
batch13_GSE214695: 14/37,252 cells express KISS1 (> 0)  [0.0%]
batch13_GSE217235: 0/22,364 cells express KISS1 (> 0)  [0.0%]
batch13_GSE217245: 1/75,337 cells express KISS1 (> 0)  [0.0%]
batch13_GSE217494: 131/157,802 cells express KISS1 (> 0)  [0.1%]
batch13_GSE218391: 1,692/101,736 cells express KISS1 (> 0)  [1.7%]
batch13_GSE218547: 190/9,113 cells express KISS1 (> 0)  [2.1%]
batch13_GSE222703: 16/39,904 cells express KISS1 (> 0)  [0.0%]
batch13_GSE223581: 862/109,204 cells express KISS1 (> 0)  [0.8%]
batch13_GSE226602: 14/282,311 cells express KISS1 (> 0)  [0.0%]
batch13_GSE226620: 332/127,828 cells express KISS1 (> 0)  [0.3%]
batch13_GSE227222: 0/20,548 cells express KISS1 (> 0)  [0.0%]
batch13_GSE228428: 88/13,518 cells express KISS1 (> 0)  [0.7%]
batch13_GSE228598: 214/124,346 cells express KISS1 (> 0)  [0.2%]
batch13_GSE229608: 212/6,804 cells express KISS1 (> 0)  [3.1%]
batch13_GSE230519: 125/43,723 cells express KISS1 (> 0)  [0.3%]
batch13_GSE230705: 12/44,910 cells express KISS1 (> 0)  [0.0%]
batch13_GSE231585: 1/46,976 cells express KISS1 (> 0)  [0.0%]
batch13_GSE235050: 4/89,600 cells express KISS1 (> 0)  [0.0%]
batch13_GSE237070: 46/78,845 cells express KISS1 (> 0)  [0.1%]
batch13_GSE237425: 255/13,150 cells express KISS1 (> 0)  [1.9%]
batch13_GSE237622: 21/59,664 cells express KISS1 (> 0)  [0.0%]
batch13_GSE239664: 1,259/59,877 cells express KISS1 (> 0)  [2.1%]
batch13_GSE239887: 604/20,288 cells express KISS1 (> 0)  [3.0%]
batch13_GSE243750_human_10X: 24/281,551 cells express KISS1 (> 0)  [0.0%]
batch13_GSE246416: 16/43,894 cells express KISS1 (> 0)  [0.0%]
batch13_GSE246662: 213/76,204 cells express KISS1 (> 0)  [0.3%]
batch13_GSE247695: 11/13,146 cells express KISS1 (> 0)  [0.1%]
batch13_GSE249361: 162/64,371 cells express KISS1 (> 0)  [0.3%]
batch13_GSE250242: 0/37,719 cells express KISS1 (> 0)  [0.0%]
batch13_GSE252959: 6/328,076 cells express KISS1 (> 0)  [0.0%]
batch13_GSE253355: 147/90,055 cells express KISS1 (> 0)  [0.2%]
batch13_GSE253857: 1/119,939 cells express KISS1 (> 0)  [0.0%]
batch13_GSE254917: 203/13,520 cells express KISS1 (> 0)  [1.5%]
batch13_GSE259219: 63/26,311 cells express KISS1 (> 0)  [0.2%]
batch13_GSE260711: 1,653/23,662 cells express KISS1 (> 0)  [7.0%]
batch13_GSE260769: 199/80,718 cells express KISS1 (> 0)  [0.2%]
batch13_GSE263372: 117/28,943 cells express KISS1 (> 0)  [0.4%]
batch13_GSE264303: 503/107,525 cells express KISS1 (> 0)  [0.5%]
batch13_GSE264508: 51/48,353 cells express KISS1 (> 0)  [0.1%]
batch13_GSE264624: 517/121,380 cells express KISS1 (> 0)  [0.4%]
batch13_GSE267209: 2/35,100 cells express KISS1 (> 0)  [0.0%]
batch13_GSE267814: 661/63,791 cells express KISS1 (> 0)  [1.0%]
batch13_GSE268903: 0/33,698 cells express KISS1 (> 0)  [0.0%]
batch13_GSE269631: 1/31,803 cells express KISS1 (> 0)  [0.0%]
batch13_GSE270788: 12/54,149 cells express KISS1 (> 0)  [0.0%]
batch13_GSE271156: 163/22,878 cells express KISS1 (> 0)  [0.7%]
batch13_GSE271257: 19/7,721 cells express KISS1 (> 0)  [0.2%]
batch13_GSE271789: 7/456,287 cells express KISS1 (> 0)  [0.0%]
batch13_GSE272409: 20/44,112 cells express KISS1 (> 0)  [0.0%]
batch13_GSE279180: 51/102,956 cells express KISS1 (> 0)  [0.0%]
batch13_GSE282122: 538/757,459 cells express KISS1 (> 0)  [0.1%]
batch13_GSE285775: 78/31,207 cells express KISS1 (> 0)  [0.2%]
batch13_HRA008003: 42/108,629 cells express KISS1 (> 0)  [0.0%]
batch13_PRJEB40416: 58/6,192 cells express KISS1 (> 0)  [0.9%]
batch13_PRJEB75160: 3/28,530 cells express KISS1 (> 0)  [0.0%]
batch13_PRJNA1073234_human: 1,591/1,089,910 cells express KISS1 (> 0)  [0.1%]
batch13_abe1a013-af7a-45ed-8c26-f3793c24a1f4: 236/34,861 cells express KISS1 (> 0)  [0.7%]
batch1_CRA001160: 677/169,305 cells express KISS1 (> 0)  [0.4%]
batch1_E-MTAB-7407: 4,592/305,054 cells express KISS1 (> 0)  [1.5%]
batch1_E-MTAB-8007: 1/38,955 cells express KISS1 (> 0)  [0.0%]
batch1_E-MTAB-8142: 220/481,664 cells express KISS1 (> 0)  [0.0%]
batch1_E-MTAB-8474: 2/9,313 cells express KISS1 (> 0)  [0.0%]
batch1_E-MTAB-9492: 1/67,308 cells express KISS1 (> 0)  [0.0%]
batch1_GSE116222: 133/12,471 cells express KISS1 (> 0)  [1.1%]
batch1_GSE123813: 413/102,335 cells express KISS1 (> 0)  [0.4%]
batch1_GSE126030: 92/75,967 cells express KISS1 (> 0)  [0.1%]
batch1_GSE134809: 37/114,659 cells express KISS1 (> 0)  [0.0%]
batch1_GSE135893: 640/179,602 cells express KISS1 (> 0)  [0.4%]
batch1_GSE136103_human: 88/106,540 cells express KISS1 (> 0)  [0.1%]
batch1_GSE144469: 4/124,175 cells express KISS1 (> 0)  [0.0%]
batch1_GSE151095: 0/1,798 cells express KISS1 (> 0)  [0.0%]
batch1_GSE152058_human: 782/126,875 cells express KISS1 (> 0)  [0.6%]
batch1_GSE157277: 21/15,905 cells express KISS1 (> 0)  [0.1%]
batch1_GSE158803_human: 57/11,890 cells express KISS1 (> 0)  [0.5%]
batch1_GSE160536: 6/12,973 cells express KISS1 (> 0)  [0.0%]
batch1_GSE178318: 420/124,674 cells express KISS1 (> 0)  [0.3%]
batch1_GSE180759: 27/98,020 cells express KISS1 (> 0)  [0.0%]
batch1_GSE196235: 24/53,912 cells express KISS1 (> 0)  [0.0%]

               experiment  measured  n_expressing  n_cells   pct
0     batch13_E-MTAB-8210      True         10993   107439  10.2
1       batch11_GSE226225      True         10592    46087  23.0
2    batch10_E-MTAB-13664      True          9611   993866   1.0
3     batch9_E-MTAB-11267      True          7676    60141  12.8
4    batch10_E-MTAB-12339      True          5039   133603   3.8
..                    ...       ...           ...      ...   ...
528     batch10_GSE141578      True             0    23728   0.0
529      batch9_GSE249622      True             0    87603   0.0
530     batch10_GSE161192      True             0     6178   0.0
531    batch9_PRJNA772047      True             0     6272   0.0
532     batch10_GSE153765      True             0     8975   0.0

[533 rows x 5 columns]

To pull the actual cells expressing a gene into an AnnData object (rather than just counting them), combine a `var_query` for the gene with the `obs_query`/`X` pattern used earlier — for example, restrict to a cell type *and* a gene, then `query.to_anndata(X_name="data")` per experiment and `ad.concat(...)` the results, exactly as `query_cell_type_in_collection` does.